### ISSUE TITLE
Dependencies: All attributes are scoped

### ISSUE THREAD

**Issue by arlimus** [inspec/inspec#1059]
https://github.com/chef/inspec/issues/888

**Comment by clintoncwolfe** [comment]
Expanding on this a bit, from internal discussions, the idea here is that an attribute is always associated with exactly one profile. 

```
# In W/inspec.yml
attributes:
 - name: A
   value: 'something'
```
If profile W includes profile C,
 and profile W defines attribute A,
 and profile C defines attribute A,
then attributes W/A and C/A are unrelated.

----

```
# In W/inspec.yml
attributes:
 - name: A
   profile: C
   value: 'something'
```
If profile W includes profile C,
 and profile W defines attribute A while naming profile C,
 and profile C defines attribute A,
then profile W sets the value of attribute C/A.
