### ISSUE TITLE
inspec exec in vagrant

### ISSUE THREAD

**Issue by anniehedgpeth** [inspec/inspec#1208]
### Description

I just have a couple of quick questions that are blocking me from getting an InSpec attributes blog post up. 
1. Can you call attributes in a `.kitchen.yml` or do you have to use the `inspec exec` command? 
2. If you have to use `inspec exec`, is there a trick to getting it to work with `vagrant`? I want to keep it simple for the tutorial and not have to use azure, so I was trying this with vagrant: 

```
$ inspec exec . -t ssh://client@127.0.0.1:2222 -i ~/.ssh/id_rsa --password=vagrant
--attrs attributes/client-attributes.yml
```

but it just wasn’t cutting it. It needed the key and the password, which is why both are there. Then this command just took me into an ssh session and asked for another password (which was not `vagrant` or `client` and didn’t run InSpec.

I also tried using the ssh_key from the `.kitchen logs`:

```

---
hostname: 127.0.0.1
port: '2222'
username: vagrant
ssh_key: "/Users/anniehedgpeth/chef_repo/cookbooks/inspec-workshop-cookbook/.kitchen/kitchen-vagrant/kitchen-inspec-workshop-cookbook-client-centos-67/.vagrant/machines/default/virtualbox/private_key"
```

But that didn't work, either. Both ways just put me into an actual ssh session instead of running InSpec on it.
### InSpec and Platform Version

InSpec 1.1.0
MacOS El Capitan 10.11.6 
### Replication Case

Here is a [draft of the tutorial](https://github.com/anniehedgpeth/anniehedgpeth.github.io/blob/master/_drafts/2016-10-05-inspec-basics-9.markdown). 
### Possible Solutions

I would love it if you could run attributes in the `.kitchen.yml` or easily run `inspec exec` on vagrant, but I have no solution to getting either of those to work. :)

Thanks!

**Comment by chris-rock** [comment]
@anniehedgpeth 
1.) attributes in `kitchen-inspec`
attributes support is not in available in test-kitchen right now. I placed an issue for that https://github.com/chef/kitchen-inspec/issues/108

2) InSpec against kitchen host

This is pretty straight-forward. The first step is to run `kitchen diagnose`

```
kitchen diagnose default-bento-centos-72
---
timestamp: 2016-10-19 09:06:07 UTC
kitchen_version: 1.13.2
instances:
  default-bento-centos-72:
    platform:
      os_type: unix
      shell_type: bourne
    state_file:
      hostname: 127.0.0.1
      last_action: converge
      port: '2222'
      ssh_key: "/Users/chartmann/Development/compliance/cookbooks/audit-cookbook/examples/kitchen/.kitchen/kitchen-vagrant/kitchen-kitchen-default-bento-centos-72/.vagrant/machines/default/virtualbox/private_key"
      username: vagrant
...
```

This will give you the hostname (kitchen maps ssh port to a local port), therefore we have `127.0.0.1`, a port `2222` and a ssh_key. Now we have all the information to connect to that host.

```
inspec exec examples/profile -t ssh://vagrant@127.0.0.1:2222 -i /Users/chartmann/Development/compliance/cookbooks/audit-cookbook/examples/kitchen/.kitchen/kitchen-vagrant/kitchen-kitchen-default-bento-centos-72/.vagrant/machines/default/virtualbox/private_key

Profile: InSpec Example Profile (profile)
Version: 1.0.0
Target:  ssh://vagrant@127.0.0.1:2222


  ✔  tmp-1.0: Create /tmp directory
     ✔  File /tmp should be directory
  ○  gordon-1.0: Verify the version number of Gordon (1 skipped)
     ○  Can't find file "/tmp/gordon/config.yaml"
     ✔  File  content should match nil
  ✔  ssh-1: Allow only SSH Protocol 2
     ✔  File /bin/sh should be owned by "root"

  File /tmp
     ✔  should be directory

Profile Summary: 2 successful, 0 failures, 1 skipped
Test Summary: 4 successful, 0 failures, 1 skipped
```

Please let us know if you need more
