### ISSUE TITLE
Profile documentation is wrong for `supports`

### ISSUE THREAD

**Issue by grimm26** [inspec/inspec#1267]
### Description

The documentation at https://github.com/chef/inspec/blob/master/docs/profiles.md indicates that you can specify multiple `supports`  to support multiple OS's:

```
> and to target all of these examples in a single inspec.yml file:
> 
> name: ssh
> supports:
>   - os-name: debian
> supports:
>   - os-name: ubuntu
>     release: 14.04
> supports:
>   - os-family: redhat
> supports:
>   - platform: aws
```

I'm guessing these are joined with an AND or something because when I specify this list I get `Failed to complete #verify action: [This OS/platform (debian) is not supported by this profile.] on default-debian-710`
If I take out everything but `os-name: debian` I am golden.

### InSpec and Platform Version

inspec 1.2.0 on OSX

### Replication Case

Create an inspec profile with the example `supports` lines and try to run the profile on one of the supported OS's.

### Possible Solutions

```
supports:
  - os-name: debian
  - os-name: ubuntu
  - os-family: redhat
```

**Comment by aalmenar** [comment]
Im currently having the same issue.

in inspec.yml:

```yaml
supports:
  - os-name: debian
    release: 8.0
  - os-name: debian
    release: 9.0
  - os-name: ubuntu
    release: 16.04
```

inspec -v
1.33.1 (This is the latest with latest chef-dk)

**Comment by adamleff** [comment]
I have been unable to reproduce this with InSpec v1.36.1. Here's what I've done:

 * Created a new profile named "supports" with `inspec init profile supports`
 * Modified the `inspec.yml` file and added the following:

```yaml
supports:
  - os-name: mac_os_x
  - os-name: ubuntu
    release: 16.04
```

 * Ran `inspec exec .` within the profile directory on my macOS machine, and the profile executed
 * Spun up a Ubuntu 16.04 Vagrant box
 * Ran `inspec exec . -t` against my Ubuntu 16.04 Vagrant box, and the profile executed
 * Spun up a Centos 7.3 Vagrant box
 * Ran `inspec exec . -t` against my Centos 7.3 Vagrant box, and it did NOT execute (as expected)

@grimm26 your issue is that you have multiple `supports` sections in your yaml file and only the last one will get loaded. Here's what the data structure looks like when I parse your YAML example:

```
[3] pry(main)> YAML.load_file('/tmp/test.yaml')
=> {"name"=>"ssh", "supports"=>[{"platform"=>"aws"}]}
```

... you can see that only the last one is kept.

@aalmenar if you can provide additional steps to reproduce this issue, I'd love to see them so I can get this fixed. I'm going to close this issue for now since it appears that everything is working. However, I'll happily re-open if you can give us some additional repro steps.

Thanks everyone!
