### ISSUE TITLE
vendoring a profile should not have archives

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#1341]
### Description

When we vendor a profile like:

```
name: meta-profile
title: Meta Compliance Profile
maintainer: InSpec Authors
copyright: InSpec Authors
copyright_email: support@chef.io
license: Apache 2
summary: InSpec Profile that is only consuming dependencies
version: 0.2.0
depends:
  - name: hardening/ssh-hardening  # defaults to supermarket
  - url: https://github.com/dev-sec/ssl-benchmark
  - name: windows-patch-benchmark
    url: https://github.com/chris-rock/windows-patch-benchmark
```

we get the following result:

```
tree examples/meta-profile 
examples/meta-profile
├── README.md
├── controls
│   └── example.rb
├── inspec.lock
├── inspec.yml
└── vendor
    ├── 01414bd307ea2f7d4dc8cd141085ba7ad61d4c3b2606d57b2dae987c1c3954cb.tar.gz
    ├── bf07978b2a5cddde79f7789881f7887f165ded8954be04e3249f26edf6447eb9.tar.gz
    └── fd3ee6bdf16d529ef9031d7bbdf23052c1b9635e8799a52a34bc1f1fe07ef921.tar.gz

2 directories, 7 files
```

If we use git as source in our `inspec.yml`, we get a different result:

```
name: meta-profile
title: Meta Compliance Profile
maintainer: InSpec Authors
copyright: InSpec Authors
copyright_email: support@chef.io
license: Apache 2
summary: InSpec Profile that is only consuming dependencies
version: 0.2.0
depends:
  - name: hardening/ssh-hardening  # defaults to supermarket
  - git: https://github.com/dev-sec/ssl-benchmark.git
  - name: windows-patch-benchmark
    git: https://github.com/chris-rock/windows-patch-benchmark.git
```

results in:
```
tree examples/meta-profile           
examples/meta-profile
├── README.md
├── controls
│   └── example.rb
├── inspec.lock
├── inspec.yml
└── vendor
    ├── 01414bd307ea2f7d4dc8cd141085ba7ad61d4c3b2606d57b2dae987c1c3954cb.tar.gz
    ├── c183d08eb25638e7f5eac97e521640ea314c8e3d
    │   ├── CONTRIBUTING.md
    │   ├── LICENSE
    │   ├── README.md
    │   ├── controls
    │   │   └── patches.rb
    │   ├── inspec.yml
    │   └── libraries
    │       └── windows_updates.rb
    └── e17486c864434c818f96ca13edd2c5a420100a45
        ├── README.md
        ├── controls
        │   └── ssl_test.rb
        └── inspec.yml

```

As defined in #1283 all vendored profiles should be always extracted and placed into `vendor` directory.

### InSpec and Platform Version

1.7.0

### Possible Solutions

Extract tars after download
