### ISSUE TITLE
`github:` source not working in inspec.yml

### ISSUE THREAD

**Issue by smith** [inspec/inspec#1769]
### Description

Using `github` in inspec.yml `depends` doesn't work.

### InSpec and Platform Version

macOS 10.12.4

InSpec 1.22.0

### Replication Case

* Create a new profile with `inspec init profile testprofile`
* Edit testprofile/inspec.yml to add:

```yaml
depends:
  - name: chef-client-hardening
    github: sliim-cookbooks/tests-chef-client-hardening
```

* Run `inspec exec testprofile`

Expected behavior: profile runs
Actual behavior: inspec exits with status code 1 and:

```
Could not fetch inspec profile in {:cwd=>"testprofile/", :backend=>#<#<Class:0x007fe9823cb6d0>:0x007fe9823b1b68>, :name=>"chef-client-hardening", :github=>"sliim-cookbooks/tests-chef-client-hardening"}.
```
