### ISSUE TITLE
Add sub-directory property to Git fetcher

### ISSUE THREAD

**Issue by trevor-vaughan** [inspec/inspec#1974]
### Description

In my experience, various users have issues with large numbers of closely related repositories being combined into a reference platform.

See https://github.com/chris-rock/acme-inspec-profile/blob/master/inspec.yml#L10-L21 for a small example.

It would be nice to be able to specify named subdirectories for those projects that wish to use a single repository for InSpec content.

Example:

```yaml
depends:
  - name: my_inspec
    url: https://github.com/me/my_inspec_bundle
    directory: special_sauce
```

This would point `my_inspec` at the `special_sauce` subdirectory of `my_inspec_bundle` and improve the user experience.
