### ISSUE TITLE
bug: multiple dependent profiles with files are out of order

### ISSUE THREAD

**Issue by Wing924** [inspec/inspec#2037]
### Description

Multiple dependent profiles with files don't work correctly.

### InSpec and Platform Version

```
inspec -> 1.25.1
```

### Replication Case

There are those profiles:

#### profile A
```ruby
# controls/spec.rb
default = yaml(content: inspec.profile.file('default-a.yml')).params
```
```yml
# files/default-a.yml
name: profle-a
```

#### profile B
```ruby
# controls/spec.rb
default = yaml(content: inspec.profile.file('default-b.yml')).params
```
```yml
# files/default-b.yml
name: profle-b
```

#### profile C
```ruby
# controls/spec.rb
include_controls 'profile-a'
include_controls 'profile-b'
```
```yml
# files/inspec.yml
name: profile c1
depends:
- name: profile-a
  path: ...
- name: profile-b
  path: ...
```
It will fail with `Cannot find file default-a.yml in profile.` . If we comment out one of `profile-a` or `profile-b`, it works.
