### ISSUE TITLE
Reporting Inspec profile runs to chef-automate

### ISSUE THREAD

**Issue by amitseth7** [inspec/inspec#2055]
### Description

Can someone guide or provide reference to article to setup .kitchen.yml to have inspec test report data to chef automate. 

I have setup a local instance to chef automate using the demo. I am able to report converges using 
data_collector.server_url: 'http://localhost/data-collector/v0/'
    data_collector.token: '93a49a4f2482c64126f7b6015e6b0f30284287ee4054ff8807fb63d9cbd1c506'
    audit_mode: :enabled

However when i do a kitchen verify , that doesnot show my test/compliance results

### InSpec and Platform Version

1.11

**Comment by alexpop** [comment]
At the moment, kitchen verify won't report the inspec results to automate.
If you want test-kitchen to send inspec profile reports to Automate, you have to use the [audit cookbook](https://supermarket.chef.io/cookbooks/audit) with the chef-client `audit_mode` disabled.

Here are some sample `.kitchen.yml` attributes for the audit cookbook:
```yml
    attributes:
      audit:
        reporter: chef-automate
        inspec_version: 1.32.1
        insecure: true
        profiles:
          - name: linux-baseline
            url: https://github.com/dev-sec/linux-baseline/archive/2.1.0.tar.gz
          - name: ssh-baseline
            url: https://github.com/dev-sec/ssh-baseline/archive/2.2.0.tar.gz
```
