### ISSUE TITLE
Support tag/version in supermarket fetcher

### ISSUE THREAD

**Issue by adamleff** [inspec/inspec#2165]
Originally submitted by @marcomancuso in chef/kitchen-inspec#134

---

Inspec profiles don't seem to be versionable in Chef-Supermarket.
It should be possible to pin a specific version of the supermarket profile in .kitchen:

```
suites:
  - name: mysuite
    verifier:
      inspec_tests:
        - name: example/myprofile
          tag: v1.0
```
Error is:

```
Could not fetch inspec profile in {:name=>"example/myprofile", :tag=>"v1.0"}.
```
Similar issue even using the version defined in .inspec.yaml

```
Could not fetch inspec profile in {:name=>"example/myprofile", :version=>"1.0.0"}.
```

It seems to be only possible when git instead:

```
suites:
  - name: mysuite
    verifier:
      inspec_tests:
        - git: https://github.com/sexample/myprofile
          tag: v1.0
```
