### ISSUE TITLE
User resource doesn't handle group names with spaces

### ISSUE THREAD

**Issue by jorritfolmer** [inspec/inspec#238]
On a Linux server that is joined to a Windows domain, users generaly are member of groups that contain spaces in their names. Eg "domain users". However, this currenly fails.

Test:

```
describe user('jfolmer') do
  its('groups') { should eq ['domain users', 'domain admins', 'denied rodc password replication group'] }
end
```

Output:

```
Failures:

  1) User jfolmer groups should eq ["domain users", "domain admins", "denied rodc password replication group"]
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

       expected: ["domain users", "domain admins", "denied rodc password replication group"]
            got: ["domain"]
```
