### ISSUE TITLE
Add supports keyword to InSpec resources and profile yaml

### ISSUE THREAD

**Issue by jquick** [inspec/inspec#2404]
### Description

This change is part of the larger platforms RFC here: #1661. This change adds in the supports field for resources and profiles. 

## Platform in profiles

Profiles can specify a list of supported platforms. This is done via the `supports` field and includes:

* `os-name`: for OS-specific platform names
* `os-family`: for OS-specific platform families
* `platform`: to target platform families or names
* `platform-name`: for specific platform names
* `platform-family`: for general platform families
* `release`: for the platform version

The `support` entries are combined via `OR` and each entry is made up of fields combined via `AND`. Example:

```
# This profile will support any version of BSD and RHELv6.
# i.e. Platform  matches  (family: bsd) OR (name: redhat AND release: 6)
- supports:
  - os-family: bsd
  - os-name: redhat
    release: 6
```

## Platforms in resources

Resources can specify a list of supported platforms. This is done via the `supports` field. It behaves just like `supports` in `inspec.yml` (section above).

Due to the Ruby language, a few names needed adjustments: `os_name`, `os_family`, `platform`, `platform_name`, `platform_family`

Full example:

```
# This resource will support any version of BSD and RHELv6.
# i.e. Platform  matches  (family: bsd) OR (name: redhat AND release: 6)
class GordonConf < Inspec.resource(1)
  name 'gordon_config'
  supports os_family: 'bsd'
  supports os_name: 'redhat', release: 6
```
