### ISSUE TITLE
YAML Resource Enhancement

### ISSUE THREAD

**Issue by rx294** [inspec/inspec#2724]
### Description
Please consider the following enhancement to the YAML resource
I will use the elasticsearch.yml file as an example here
On the yml file for example following three definitions are valid

```
xpack:
  security:
    authc:
      realms.pki1.type: pki
      realms.pki1.order: 1
```
```
xpack.security.authc.realms.pki1.type: pki
xpack.security.authc.realms.pki1.order: 1
```
```
 xpack:
  security:
    authc:
      realms:
        pki1:
          type: pki
          order: 1
```
However the YAML resource exposes these values differently in each case.
```
case 1: yaml('elasticsearch.yml').xpack["security"]["authc"]["realms.pki1.type"]
case 2: yaml('elasticsearch.yml')['xpack.security.authc.realms.pki1.type']
case 3: yaml('elasticsearch.yml').xpack['security']['authc']['realms']['pki1']['type']
```

This will make it very hard to write exhaustive tests to check if the right params are set.

Please consider a enhancement that would allow for tests such as 
yaml('elasticsearch.yml')['xpack.security.authc.realms.pki1.type'] for all possible types of definitions.

### InSpec and Platform Version
2.0.17
### Possible Solutions

May be a solution based on Hashie::Mash can take care of this easily.

@aaronlippold
