### ISSUE TITLE
Processes resource doesn't handle user or state

### ISSUE THREAD

**Issue by thomascate** [inspec/inspec#295]
Testing on Ubuntu 14.04 and OSX 10.10.5 with the following code

Ubuntu

```
describe processes('init') do
  its('user') { should eq 'root' }
  its('list.length') { should eq 1 }
  its('state') { should eq 'R<' }
end
```

OSX

```
describe processes('launchd') do
  its('user') { should eq 'root' }
  its('list.length') { should eq 3 }
  its('state') { should eq 'R<' }
end
```

The process is found and list length returns correctly, however user and state return

```
Failures:

  1) Processes user
     Failure/Error: inner_subject.send(attr)

     NoMethodError:
       undefined method `user' for Processes:#<Class:0x007f82648669e0>
     # test_spec.rb:2:in `block (2 levels) in load'
     # /Library/Ruby/Gems/2.0.0/gems/inspec-0.9.5/lib/inspec/runner.rb:97:in `run_with'
     # /Library/Ruby/Gems/2.0.0/gems/inspec-0.9.5/lib/inspec/runner.rb:93:in `run'
     # /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
     # /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
     # /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
     # /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'

  2) Processes state
     Failure/Error: inner_subject.send(attr)

     NoMethodError:
       undefined method `state' for Processes:#<Class:0x007f82648669e0>
     # test_spec.rb:4:in `block (2 levels) in load'
     # /Library/Ruby/Gems/2.0.0/gems/inspec-0.9.5/lib/inspec/runner.rb:97:in `run_with'
     # /Library/Ruby/Gems/2.0.0/gems/inspec-0.9.5/lib/inspec/runner.rb:93:in `run'
     # /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
     # /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
     # /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
     # /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
```
