### ISSUE TITLE
git-type profile dependencies do not implement the 'tag' option

### ISSUE THREAD

**Issue by Wing924** [inspec/inspec#2986]
### 🎛 Description

**Choose one:** is this a 🐛 bug

According to inspec docs, git profile dependencies support `version`.
```yaml
depends:
- name: git-profile
  git: http://url/to/repo
  branch:  desired_branch
  tag:     desired_version
  commit:  pinned_commit
  version: semver_via_tags
```
<https://www.inspec.io/docs/reference/profiles/>

But it seems not be implemented.
```ruby
    def resolved_ref
      @resolved_ref ||= if @ref
                          @ref
                        elsif @branch
                          resolve_ref(@branch)
                        elsif @tag
                          resolve_ref(@tag)
                        else
                          resolve_ref('master')
                        end
    end
```
<https://github.com/chef/inspec/blob/master/lib/fetchers/git.rb#L73>

### 🌍 InSpec and Platform Version

`2.1.54`
