### ISSUE TITLE
Profile option "inspec_version" is only recognised  from the inspec.yml being executed and not any dependent profiles

### ISSUE THREAD

**Issue by skpaterson** [inspec/inspec#3066]
### 🎛 Description

🐛 bug report 

Inspec profiles using "depends" don't pick up "inspec_version" from the dependent profiles.  If a dependency has a minimum inspec version specified, it would be desirable if this was respected.

### 🌍 InSpec and Platform Version

2.1.78

### 🤔 Replication Case

When a profile has a 'depends' section such as:
```
depends:
  - name: my-profile
    path: ../../../
```
And the dependent profile inspec.yml at the appropriate path includes "inspec_version" such as:
```
inspec_version: '>= 2.1.78'
```
This is seemingly not respected when executing the original profile.  The easiest way to replicate this is to have a setup as above with the dependent profile set to a new, non-existing version such as:
```
inspec_version: '>= 99.1.78'
```

### 💁 Possible Solutions

To work around this the "inspec_version" parameter has to be inserted in the inspec.yml being executed.  Presumably the highest version of all listed dependencies should be the one enforced before executing the inspec tests.

**Comment by jquick** [comment]
This should happen in 3.0 when we rebuild how the dependencies are pulled/ran

**Comment by Nik08** [comment]
I followed the above steps and added `inspec_version: '>= 99.1.78'` on the dependent profile:

Main profiles (metadata file):

```
name: inheritance
title: InSpec example inheritance
maintainer: Chef Software, Inc.
copyright: Chef Software, Inc.
copyright_email: support@chef.io
license: Apache 2 license
version: 1.0.0
depends:
  - name: profile_a
    path: ../profile_a
  - name: profile_b
    path: ../profile_b


```
Dependent profiles (metadata file)
```
name: profile_a
title: InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile
version: 0.1.0
inspec_version: '>= 99.1.78'
depends:
  - name: profile_c
    path: ../profile_c
```

I am using InSpec version `4.41.2` and this seems to be working. It skipped `profile_a` and ran all other successfully.
This is not reproducible and could be closed.
