### ISSUE TITLE
inspec vendor not working for git dependencies

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#3067]
### 🎛 Description

Create a new `inspec.yml` that looks like:
```
name: gcp-compliance-example
title: InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile
version: 0.1.0

depends:
  - name: gcp
    git: git@github.com:inspec/inspec-gcp.git 
```

Then run `inspec vendor .`:
```
inspec vendor . 
Dependencies for profile . successfully vendored to vendor
```

Shows that the directory structure is not correct:

```
tree vendor -L 2
vendor
└── 836da0196e894c980153f729d7a1f476ed7e43b8
    └── d20180517-36416-1avoz2b

2 directories, 0 files
```

The subdirectory `d20180517-36416-1avoz2b` should not exist and everything should be in `836da0196e894c980153f729d7a1f476ed7e43b8` 

### 🌍 InSpec and Platform Version

2.1.80

### 🤔 Replication Case

See above

### 💁 Possible Solutions

This is probably an issue in our git fetcher

### 💻 Stacktrace

n/a
