### ISSUE TITLE
RFC unified attributes

### ISSUE THREAD

**Issue by arlimus** [inspec/inspec#3176]
### Description

Currently attributes are defined on a per-file basis:

```ruby
> controls/a.rb
user = attribute('user', required: true)
...
```

For attributes that are shared across files, this leads to a lot of duplication and potential overrides:

```ruby
> controls/b.rb
user = attribute('user', required: true)
...
```

### Goals

- define attributes in one place only and make them accessible across all inspec files
- prevent accidental attribute overrides 

### Design

`inspec.yml` will define the attributes:

```yaml
attributes:
- name: NAME
  required: [false]/true
  type: [any]/string/numeric/boolean/regex/array/hash
  default: []
```

Attributes are then used in regular control files:

```
attribute(NAME)
```

**Full example:**

`inspec.yml` contains:

```yaml
attributes:
- name: port
  type: int
  default: 443
```

`controls/example.rb` contains:

```ruby
control ssl(port: attribute('port')) do
  it { should be_enabled }
end
```

### Action Items
1) Implement new yml attribute definition
 - include basic validation (regex)
2) Deprecate the inline control attribute definition

### References

https://github.com/inspec/inspec/issues/719

**Comment by aaronlippold** [comment]
I think this is a great solution. The one thing I might add is pattern
definitions so that we can do some sort of input validation and or default
validation. Is perhaps a string or a number has to match a particular
pattern that would be very useful to enforce standards

**Comment by clintoncwolfe** [comment]
I like validation, too.  In the past, I've worked with validators that work like this:
validation: regex/array/proc

The array would be an enumeration of valid values.

We can't really have a Proc in YAML, so that's probably out.  We could reference a method name in a library file.  That all sounds like a nice later enhancement.

**Comment by aaronlippold** [comment]
the validation would be in `inspec check` process

I am not sure how we would define the patterns outside regex or accepted values in an array or hash or whatnot.

**Comment by aaronlippold** [comment]
@arlimus et all, one thing we would like to add to this is the long awaited ability to pass attribute values ( such as `user` or `password` ) via the CLI directly. ( i.e. not using a file ) so we can ease the integration into the CI/CD pipeline. We have the ability now via a json file but being able to pass single attribute values via the cli would be very useful. We do this in kitchen-inspec now but don't have support in the CLI for it.

**Comment by aaronlippold** [comment]
In reference to #3185 and #1976 and the other 'sensitive' related requests, perhaps this would be a good time to cover this issue as well. In thinking about it I think we need to have two modes - the default to redact sensitive information in all reporting and an override property of `show_sensitive` for testing purposes. Given the new approach of centralized attributes in the `inspec.yml` I think a structure along the lines of:
```yaml
attribute_opts:
- show_sensitive: [false]/true
attributes:
- name: NAME
  required: [false]/true
  sensitive: [false]/true
  type: [any]/string/int/numeric/boolean/regex/array/hash
  default: []
  validation: [type]:[pattern]
```
I think this should allow us to easily centralize the reporters to show and not show sensitive data.

This is actually ***very*** important as the output of our data could have sensitive data which could be a **_triggering event_** for raising the sensitivity of the data.

This connects to InSpec's ability to operate in a multi-zone security space - i.e. I don't want my results data to trigger a separation of concerns type event.
 
Thoughts?

**Comment by aaronlippold** [comment]
(I know this is reaching a bit outside the scope of the original RFC but just something to put on as a follow on task or at least a discussion or 'best practice' issue...)

The ruby type of attributes has also become an issue when using shared attributes. i.e. that the default nature of doing caps to make the attribute distinguishable in the code has the side effect of making it a ruby constant, and thusly we have seen odd behavior across controls and how these load order effects the value of the variable. 

So in a case where we use a common attribute name like - 'FILE_PATH' - which changes in the scope of the control we have tripped over this.

```
ATTRIB =  attribute('attrib', desc: "ping", default: "pong") 
```
Our work around has been to ensure that these 'shared attributes' are not ruby constants but perhaps in this new model we could do something to help with this.

Our use case has been things like the `auditd` rules and and other control `groups` that have a common pattern and we are working to standardize the testing method and implementation of the code for that group.

Just something to think about.

see: https://github.com/djhaynes/inspec-profile-disa_stig-el7/issues/39

**Comment by aaronlippold** [comment]
In the below example, in my `attributes.yml` I would create the general `audit_file` attribute the properties - leaving out the default value - which we could make inSpec understand that at least one control in the profile should set the value given it's required state but lack of centralized default value.
```yaml
attributes:
- name: audit_file
  required: true
  sensitive: false
  type: file_path
  default: []
  validation: file_path:[*.*]
 ```
I would then set the path in the control as this is the right context / scope - else `inspec validate` would throw a warning.

```ruby
  audit_file = '/usr/sbin/setsebool'

  if file(audit_file).exist?
    impact 0.5
  else
    impact 0.0
  end

  describe auditd.file(audit_file) do
    its('permissions') { should_not cmp [] }
    its('action') { should_not include 'never' }
  end if file(audit_file).exist?

  # Resource creates data structure including all usages of file
  perms = auditd.file(audit_file).permissions

  perms.each do |perm|
    describe perm do
      it { should include 'x' }
    end
  end if file(audit_file).exist?

  describe "The #{audit_file} file does not exist" do
    skip "The #{audit_file} file does not exist, this requirement is Not Applicable."
  end if !file(audit_file).exist?
```

**Comment by aaronlippold** [comment]
@arlimus @jquick @chris-rock as a side note or a separate issue - do you see the pattern ( which we are using a lot ) here where we have `impact` going to `0` and a connected describe block on that condition as the `N/A` condition for the controls. 

I would love to make that logic easer with some built in functions that could take an impact value, a condition, a message to make overall maintenance and upkeep easer.

**Comment by aaronlippold** [comment]
For the attribute types - would it be a bridge too far to have:
```yaml
attributes:
- name: NAME
  required: [false]/true
  sensitive: [false]/true
  type: [any]/string/int/numeric/boolean/regex/array/hash/file/file_path/directory
  default: []
  validation: [type]:[pattern]
```

I know `file` and `file_path` may be the same thing but something like `/etc/fstab` vs `inittab` vs `/etc` is what I am thinking.

Then - perhaps - could we use the ruby `is_a` object methods to detect known types like `file`, `directory`, `path` etc?
