### ISSUE TITLE
Inspec does not properly re-cache compliance dependencies

### ISSUE THREAD

**Issue by jquick** [inspec/inspec#3311]
### 🎛 Description

🐛 bug report 

When using a compliance dependency the URL of the compliance server is written to the `inspec.lock` file. This make inspec think its a traditional url fetch when trying to re-download the dependency. This is the current `inspec.lock` file which does not work:

```
---
lockfile_version: 1
depends:
- name: jhud_child
  resolved_source:
    compliance: admin/jhud-test
    url: https://ec2-34-221-162-96.us-west-2.compute.amazonaws.com/api/v0/compliance/profiles/tar
    sha256: 39bdd3798f5de06a9c364dc135a0787c605b5e702af88f6fad494dec3a63eb29
  version_constraints: []
```

Removing the URL line make the fetchers work again and properly call out to the compliance server.

### 💁 Possible Solutions

Remove the url from being written to the lock file or change the fetcher priority to look at compliance first.
