### ISSUE TITLE
Support http basic auth for URL based dependency resolution

### ISSUE THREAD

**Issue by frezbo** [inspec/inspec#3342]
### 🎛 Description

**Choose one:** 🙋 feature request?

Support http basic auth for URL based dependency resolution

**Comment by frezbo** [comment]
I guess we can close this now.

**Comment by micheelengronne** [comment]
Is it possible to specify credentials via environment variables ? I would not like them to appear in the lockfile.

**Comment by frezbo** [comment]
@micheelengronne I use ERB templating like this:

```yaml
depends:
  - name: profile
    url: <%= "#{ENV.fetch('INSPEC_REPO_URL', 'https://artifactory.example.repo.com/artifactory/local-release')}/profile-0.4.12.tar.gz" %>
    username: <%= ENV['ARTIFACTORY_USERNAME'] %>
    password: <%= ENV['ARTIFACTORY_API_KEY'] %>
```
