### ISSUE TITLE
Attribute passing and export via namespace

### ISSUE THREAD

**Issue by jquick** [inspec/inspec#3410]
### 🎛 Description

🙋 feature request?

It would be nice a if a wrapper profile could override defaults in the `inspec.yml` for its dependents. 

### 💁 Possible Solutions

Add a new field to the attribute section of the `inspec.yml` called `overwrite`. When true this attribute will overwrite any dependent profile attributes with the same exact name cascading.

inspec.yml
```
attributes:
  name: stig
  default: 12345
  overwrite: true
```

Running `inspec json` on said profile should show the overwrite attributes

Another option that has come up is namespacing in the parent inspec.yml:
```
attributes:
  - name: profile2.stig
    default: 12345
  - name: stig
    default: 54321
```

We should also namespace the `-attrs` accordingly:
Attr.yml
```
name.profile1: fred
name.profile2: bob
```

We should also make `inspec json` export namespace'd attributes accordingly

**Comment by arlimus** [comment]
```
linux-profile -> mysql-profile
[user]                [user]
                     -> postgres-profile
                         [user]

```

mysql profile inspec.yaml:

```yaml
attributes:
  - name: user
    value: mysql
```

**case 1: delimiter**
linux profile `inspec.yml`:

```yaml
depends:
  - name: mysql-profile
    git: ...
  - name: postgres-profile
    compliance: ...
attributes:
  - name: user
    value: username
  - name: mysql-profile.user
    value: mysql-ubuntu
```

nope because: arbitrary delimiter in a file that gives us structured data is a bad idea

**case 2: hash**
linux profile `inspec.yml`:

```yaml
depends:
  - name: mysql-profile
    git: ...
  - name: postgres-profile
    compliance: ...
attributes:
  - name: user
    value: username
  - name: user
    profile: mysql-profile
    value: mysql-ubuntu
```

**case 3: depends**
linux profile `inspec.yml`:

```yaml
depends:
  - name: mysql-profile
    git: ...
    attributes:
      - name: user
        value: mysql-ubuntu
  - name: postgres-profile
    compliance: ...
    attributes:
      - name: user
        value: postgres-ubuntu
attributes:
  - name: user
    value: username
```

Team likes case 2 and 3; let's go with case 3 
Open items:
- warn on unused attributes in the profile? => catches cases where users accidentally forgot the to specify the profile namespace => maybe in inspec check?

**Comment by arlimus** [comment]
inspec.yml
```yaml
attributes:
- name: user
  profile: mysql
  value: bob
```
 
**inspec <3**

attrs.yml:
```yaml
user: bob
```

**case 2**

attrs.yml:
```yaml
- name: user
  profile: mysql
  value: bob
```

**case 3.1**

attrs.yml:
```yaml
- profile: mysql
  attributes:
  - name: user
  - value: bob
```

**case 3.2**

attrs.yml:
```yaml
wrapper:
- name: user
  value: ubuntu
mysql:
- name: user
  value: bob
```

impact: not backwards compatible?

**behavior**

- if you see any parts of the old structure

  new structure: 
    Attributes := Map{PROFILE_NAME:[]Attrs}  Attrs:=Map{name, value}

  1. warn the user
  2. namespace under the profile that it is being run against
  - support this model for InSpec 3.x

**Comment by jquick** [comment]
We are going with case 3 for `inspec.yml` case 3.2 for `attrs` file and this format for `inspec json`:
```Yaml
  "attribute": [
    "wrapper-override": {
      "name": "dog",
      "value": "hippy",
      "type": "string",
      "required": "true"
    },
    "myprofile": {
      "name": "dog",
      "value": "bowser"
    }
  ],
```
