### ISSUE TITLE
Cannot archive profile when attributes have no default attribute

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#3464]
### 🎛 Description

this a 🐛 bug report

When using unified attributes (I think applies to normal attribute behaviour too, but not tested) without default values, and required, the profile cannot be archived with `inspec archive` 

Use https://github.com/dev-sec/cis-dil-benchmark/pull/55 and change the inspec.yml to match (no default value provided)

```yml
attributes:
  - name: cis_level
    required: true
    description: 'CIS profile level to audit'
    type: numeric
```

Then InSpec returns the following error

```bash
$ inspec archive cis-dil-benchmark
Attribute 'cis_level' is required and does not have a value.
```

### 🌍 InSpec and Platform Version

InSpec 2.3.8 (3248af1f)

### 🤔 Replication Case

As described above.

### 💁 Possible Solutions

ignore missing attributes when used in archive mode 

### 💻 Stacktrace

n/a
