### ISSUE TITLE
Service Resource fails when Docker Container

### ISSUE THREAD

**Issue by darkn3rd** [inspec/inspec#3544]
### 🎛 Description 🐛

Cannot verify service on Ubuntu 16.04 docker container, but works with vagrant.

### 🌍 InSpec and Platform Version

```2.2.70```

### 🤔 Replication Case

I was using Test Kitchen to drive the tests.   The YAML file below pulls the docker image ubuntu:16.04.  Kitchen, it then does some steps to enable ssh and sudo. 

```yaml
---
driver:
  name: docker

provisioner:
  name: chef_zero

verifier:
  name: inspec
  sudo: true

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[ez_apache::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
```

Simple Chef Cookbook recipe that does:

```ruby
package apache2
```

And simple Inspec script:

```ruby
control 'apache-01' do
  impact 1.0
  title 'Apache should be running'
  desc 'Apache should be running.'
  describe service(apache.service) do
    it { should be_installed }
    it { should be_running }
  end
end
```

### Actual Results

```
Target:  ssh://kitchen@localhost:32769

  ×  apache-01: Apache should be running (2 failed)
     ×  Service apache2 should be installed
     expected that `Service apache2` is installed
     ×  Service apache2 should be running
     expected that `Service apache2` is running
```

### Expected Results

If I use vagrant, it works, using Chef bento box.  I want to get this working on docker for CI purposes.

```yaml
---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[ez_apache::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
```

### 💁 Possible Solutions

Not sure.
