### ISSUE TITLE
passing attributes from one profile to another

### ISSUE THREAD

**Issue by moodwrench** [inspec/inspec#3934]
### 🎛Description 

**Im unsure if this is a 🐛 bug report or 🙋 feature request or my own stupidity

Im having trouble passing an attribute defined in the inspec.yml of one profile from a call using include_controls in another profile.  I've been trying and I can't seem to find any way to set the variables other then the cli which will not work for us as we are using inspec via Chef Kitchen.

### 🌍 InSpec and Platform Version

inspec version: 3.2.6
Ubuntu 16.04.3 LTS

### 🤔 Replication Case

profile1/inspec.yml 
```
name 'profile1'

attributes:
  - name: my_setting
    type: boolean
    default: false
```

profile1/controls/profile1.rb
```
control 'test' do
  if attribute('my_setting')
    # do thing 1
  else
    # do thing 2
  end
end
```

profile1/inspec.yml 
```
name 'profile2'

depends:
  - name: profile1
    path: test/shared/profile1

attributes:
  - name: my_setting
    type: boolean
    value: true
```

profile2/controls/profile2.rb
```
include_controls 'profile1'
```
