### ISSUE TITLE
Add enum to input types

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#4029]
### 🎛 Description

Now that inputs have optional type checking, a great feature would be allowing selection from a list of valid options.

If the word 'enum' is too technical, consider 'choice'.

In DSL
```ruby
input('favorite_fruit', type: :enum, choices: ['apple', 'banana', 'cherry'])
```

In metadata
```yaml
inputs:
- name: favorite_fruit
  type: enum
  value: pizza # Default value
  choices:
    - pizza
    - eggplant parmesean
    - steamed bok choi
```

### 🌍 InSpec and Platform Version

4.3.2
