### ISSUE TITLE
NPM Resource does not report on local package installations properly

### ISSUE THREAD

**Issue by russellseymour** [inspec/inspec#4290]
The NPM resource allows a path to be set to find the node_modules in a project directory. The command that it uses works on the command line.

cd <PROJECT_DIR> && npm ls --json <PACKAGE_NAME>

```json
{
  "dependencies": {
    "sprintf-js": {
      "version": "1.1.2",
      "from": "sprintf-js@latest",
      "resolved": "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.1.2.tgz"
    }
  }
}
```

But when run in InSpec the test states that the package is not installed:

```ruby
describe npm('azure-storage', path: '/usr/local/camsa/statsd/azure-queue') do
   it { should be_installed }
end
```

```
  Npm Package azure-storage
     [FAIL]  should be installed
     expected that `Npm Package azure-storage` is installed
```

**Comment by clintoncwolfe** [comment]
I'm afraid I'm an npm noob, so I'm casting about a bit, but here is my understanding - please correct me if this is incorrect:

Repro setup:
```
# (Ensure npm is installed)
# then...
mkdir temp-npm
cd temp-npm
npm init --y
npm install underscore
cd ..
```

And then:
```
[cwolfe@lodi inspec-incident]$ cd temp-npm && npm ls --json underscore
{
  "name": "temp-npm",
  "version": "1.0.0",
  "dependencies": {
    "underscore": {
      "version": "1.9.1",
      "from": "underscore",
      "resolved": "https://registry.npmjs.org/underscore/-/underscore-1.9.1.tgz"
    }
  }
}
```

This seems to work for me:
```
[cwolfe@lodi inspec-incident]$ bundle exec inspec shell
Welcome to the interactive InSpec Shell
To find out how to use it, type: help

You are currently running on:

    Name:      mac_os_x
    Families:  darwin, bsd, unix, os
    Release:   18.5.0
    Arch:      x86_64

inspec> describe npm('underscore', path:'temp-npm') do
inspec>   it { should be_installed }
inspec> end

Profile: inspec-shell
Version: (not specified)

  Npm Package underscore
     ✔  should be installed

Test Summary: 1 successful, 0 failures, 0 skipped
inspec> exit
```

**Comment by clintoncwolfe** [comment]
@russellseymour am I doing something wrong, or too simply? Perhaps we will need to look at your specific setup?

**Comment by russellseymour** [comment]
@clintoncwolfe I will test my setup again as this is what I am trying to do
The only difference is that I am setting a full path in `path:` on the resource but I cannot see that making a difference
I will try with the interactive shell as you have done and see what I come up with.

**Comment by kekaichinose** [comment]
@russellseymour any follow-up here, sir?

**Comment by kekaichinose** [comment]
@russellseymour just wanted to track that we slacked on status, and you'll look to get to this by EOW. We want to make sure our issues don't age out too much so appreciate your help here, sir.

**Comment by russellseymour** [comment]
Hello, my apologies for not getting back to you sooner about this.

I have done some testing and I think the problem is related to the verifier for Test Kitchen.

As before I have the following test in my suite:

```
  describe npm('sprintf-js', path: '/usr/local/camsa/statsd/azure-queue') do
    it { should be_installed }
  end
```

When I run `kitchen verify` it fails with the error:

```
  Npm Package sprintf-js
     [FAIL]  should be installed
     expected that `Npm Package sprintf-js` is installed
```

As @clintoncwolfe was able to get a similar setup working, I decided to login into the machine (using `kitchen login`) and run the same test. The strange thing is that the above test works when using `inspec shell` on the machine:

```
Welcome to the interactive InSpec Shell
To find out how to use it, type: help

You are currently running on:

    Name:      ubuntu
    Families:  debian, linux, unix, os
    Release:   18.04
    Arch:      x86_64

inspec> describe npm('sprintf-js', path: '/usr/local/camsa/statsd/azure-queue') do
inspec>   it { should be_installed }
inspec> end

Profile: inspec-shell
Version: (not specified)

  Npm Package sprintf-js
     ✔  should be installed

Test Summary: 1 successful, 0 failures, 0 skipped
```

This is what has lead me to think that there is a problem with the verifier when the tests are run by Test Kitchen. For more information here are the versions of software on workstation and the target server:

**Workstation**

| Component | Version |
|---|---|
| Test Kitchen | 2.2.5 |
| Kitchen Inspec | 1.1.0 |
| Inspec | 4.7.3 |

**Server**

| Component | Version |
|---|---|
| Inspec | 4.6.4 |
| Chef Infra | 15.1.36 |

When running Inspec I used the one that is embedded with Chef Infra.

I am not sure if this means this bug needs to be moved to Kitchen Inspec, I will leave that up to the team.

**Comment by russellseymour** [comment]
I saw that there are two newer versions of `kitchen-inspec` on the GH release page for the repo.

I thought I would try a newer version in case that fixed the issue above, however it appears that versions 1.1.1 and 1.2.0 have not been publied to RubyGems. Only version 1.1.0 is available there.

**Comment by clintoncwolfe** [comment]
FYI we have published kitchen-inspec 1.2.0 (which has inputs support) to rubygems. HOWEVER, continue to use `attributes` for now, as inspec itself does not support inputs, until #3856 is resolved.

**Comment by russellseymour** [comment]
I have just performed the above tests again using `kitchen-inspec` version 1.2.0 and the problemstill exists. My tests for NPM modules installed in a directory fail when using `kitchen-inspec`.

**Comment by miah** [comment]
@russellseymour could you please provide the failing test? feel free to ping me on slack. I'd like to get the failing test into our test harness then we can work on resolution.

**Comment by clintoncwolfe** [comment]
Specifically the two pieces we are missing in order to reproduce your setup:
 * a cookbook or whatever else you're using to to setup your test-kitchen image - without this, we're just guessing at what and how the npm stuff is installed
 * your .kitchen.yml file - without this, we don't know how InSpec is being called, and that is the crucial part of the bug here.

Thanks!

**Comment by kekaichinose** [comment]
@russellseymour could you please provide the missing pieces of info we need here, sir?

**Comment by russellseymour** [comment]
The cookbooks and tests are in GitHub at https://github.com/chef-partners/camsa-setup

Attributes file for the NPM packages that need to be installed - https://github.com/chef-partners/camsa-setup/blob/master/cookbooks/camsa/attributes/chefserver.rb

Recipe file that installs the packages - https://github.com/chef-partners/camsa-setup/blob/master/cookbooks/camsa/recipes/monitoring.rb#L71-L78

The InSpec test checking that the packages have been installed - https://github.com/chef-partners/camsa-setup/blob/master/test/integration/camsa/monitoring.rb#L44-L50
(At the moment they are commented out as they do not work)

Finally the kitchen file - https://github.com/chef-partners/camsa-setup/blob/master/kitchen.yml

**Comment by clintoncwolfe** [comment]
Hey @russellseymour - just wanted to let you know this is being actively worked. Thanks for all the materials - I don't think I can reproduce your whole setup (Azure + Automate + ChefServer + CAMSA), but from the excellent set of things you provided, I can see that it boils down to a Chef install of NPM packages (from a custom resource included with the nodejs cookbook), with a custom path that is interpolated from another attribute; later, InSpec uses an NPM resource with a custom path to verify those packages. At the moment it's unclear whether the interpolation, the custom chef resource, or the inspec resource is malfunctioning. I've made a minimal test case, with just a cookbook, profile, and kitchenfile. and should know more soon.

**Comment by clintoncwolfe** [comment]
OK, my minimal test case is at https://github.com/clintoncwolfe/npm-inspec-repro . Unfortunately, I didn't find anything - after I managed to get it to converge, it did indeed pass the inspec tests. So, at this point we're still at a a "no repro" status. 

This was under test-kitchen 2.3.2, inspec 4.16.0, and kitchen-inspec 1.2.0 . It is conceivable that we may have simply fixed it, but I don't think we were working on anything near this functionality recently.

Please have a look - I radically simplified, obviously, so if I trimmed out the part that may be defective, please do let me know. I'd like to get this resolved for you.

**Comment by russellseymour** [comment]
@clintoncwolfe  Thanks for this

I will take a look at your repo and see if there is soimething I am missing or have mis-configured along the way

**Comment by russellseymour** [comment]
With the help of @clintoncwolfe test repo, I think I have started to narrow down where the issue is. I _think_ it has something to do with the InSpec verifier in Test Kitchen.

I was successfully able to run Test Kitchen and the tests from the `npm-inspec-repro` when using the `inspec-dokken` driver.

So then I changed this over to using the `inspec-azurerm` driver and I got the same error messages as I have had in the past.

![image](https://user-images.githubusercontent.com/791658/64627834-3f563b00-d3e8-11e9-8f48-a008e9f9eac8.png)

As this seems really strange, I then ran the tests directly using InSpec in remote mode with the following command:

`inspec exec .\test\integration\default -t ssh://azure@52.151.90.105 -i C:\Users\russells\.ssh\id-kitchen-azurerm`

Now the tests pass!!!

![image](https://user-images.githubusercontent.com/791658/64627957-7298ca00-d3e8-11e9-901d-3554ebebf985.png)

To double check things I have also performed some interactive tests using `inspec shell`:

![image](https://user-images.githubusercontent.com/791658/64628423-492c6e00-d3e9-11e9-9ee2-b5361a7660c3.png)

This also worked.

As I am using an SSH key and ENV vars to configure parts of Test Kitchen for use with the AzureRM driver I do no tmind sharing my kitchen file:

```
---
driver:
  name: azurerm
  subscription_id: <%= ENV['AZURE_SUBSCRIPTION_ID'] %>
  location: <%= ENV['AZURE_LOCATION'] || 'uksouth' %>
  machine_size: Standard_D2s_v3

transport:
  ssh_key: ~/.ssh/id-kitchen-azurerm

provisioner:
  name: chef_zero
  log_level: <%= ENV['CHEF_LOG_LEVEL'] || 'info' %>
  product_name: chef
  product_version: 15

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04
    driver:
      image_urn: Canonical:UbuntuServer:18.04-LTS:latest

suites:
- name: default
  run_list:
  - recipe[os_prepare]
  - recipe[npm_installs]
  verifier:
    inspec_tests:
      - test/integration/default
```

I can appreciate that this is a werid problem as it seems to only manifest itself when using the Test Kitchen InSpec verifier over an SSH transport and only with the `npm` resource. I have not yet tried this against a different remote machine using SSH, e.g. AWS, but I will give it a go and report back.

**Comment by russellseymour** [comment]
I have just verified that this is an issue with AWS as well. I get exactly the same errors as before.

![image](https://user-images.githubusercontent.com/791658/65052688-ba789d80-d962-11e9-85cf-dd44fd50b6ad.png)

The `kitchen.yml` file this test looks like

```
---
driver:
  name: ec2
  aws_ssh_key_id: AWS_KP
  region: eu-west-2
  security_group_ids: ['sg-07d06bd45a0b9fa7f']

transport:
  ssh_key: ~/.ssh/AWS_KP.pem
  username: ubuntu

provisioner:
  name: chef_zero
  log_level: <%= ENV['CHEF_LOG_LEVEL'] || 'info' %>
  chef_license: accept
  product_name: chef
  product_version: 15

verifier:
  name: inspec
  reporter:
    - cli

platforms:
  - name: ubuntu-18.04
    driver:
      image_id: ami-012d95ddd53c98e0e
      instance_type: t2.medium

suites:
- name: default
  run_list:
  - recipe[os_prepare]
  - recipe[npm_installs]
  verifier:
    inspec_tests:
      - test/integration/default
```
