### ISSUE TITLE
Waivers Step 1: Input File & CLI

### ISSUE THREAD

**Issue by kekaichinose** [inspec/inspec#4409]
This is part of epic #4408.

### User Story
As an Operator, I need to have a way to define and read in waivers so I can apply them to my profiles when doing an inspec run.

### Acceptance Criteria
* define a file format (e.g. toml, yaml, etc) to store waiver configurations
  * a waiver is applied at the control level
  * a waiver entry will contain the following data
    * __Control ID_Name__ - the ID and Title of the control to be waived
    * __Expiration Date__ - the date when the waiver is set to expire
    * __Waiver Justification__ *(optional)* - a way to allow users to justify the waiver (i.e. why the given control must be waived)
    * __Skip run switch__ - allow users to skip evaluating the waived control
* be able to read in waiver file from command line

**Comment by clintoncwolfe** [comment]
```
Control ID_Name - the ID and Title of the control to be waived
```
Controls have both an ID and a title - which value will be available in this field? I recommend ID.

**Comment by galenemery** [comment]
I'm ➕ for ID

**Comment by zenspider** [comment]
+ Input doc
  + a cli option
  + need to pin down a format
    + Control id (name?)
    + Optional expiration date
    + Waiver reason blurb
    + Skip boolean (should this run and a failure does NOT affect the overall result vs should this just not run)
  + straightforward

Draft file format:

```yaml
xccdf_org.cisecurity.benchmarks_rule_1.21_something_else:
  expiry_date: 2019-09-15
  justification: We don't like this one
  skip_run: true

xccdf_org.cisecurity.benchmarks_rule_1.1.1.4_Ensure_mounting_of_hfs_filesystems_is_disabled:
  justification: We don't like this one
```
