### ISSUE TITLE
inspec archive command fails with stack level too deep error

### ISSUE THREAD

**Issue by TheLunaticScripter** [inspec/inspec#4591]
`inspec archive` when using a profile that has a dependency on a profile in Automate will fail to archive giving the error below.
```
Traceback (most recent call last):
C:/opscode/inspec/bin/inspec: stack level too deep (SystemStackError)
```

# Describe the problem
When running `inspec archive . --overwrite -o "test.tar.gz"` against a profile with the following `inspec.yml` file

```
name: effortless-a2-profile-test
title: Effortless Automate CIS profile Test
version: 1.0.0

depends:
  - name: cis-rhel7-level1-server
    compliance: admin/cis-rhel7-level1-server
```
I have tested this and it works with InSpec version `4.16.0` but doesn't work with `4.17.6` or higher.
