### ISSUE TITLE
Add the ability to set expected patterns for inputs

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#5014]
While setting shared inputs in my profiles I would like to do input validation to enforce expected data.

To start with - the easy cases 

Number [0-9] or 1, 3, 5 
String %r{}

The harder case would be JSON, hashes with various data types and then again patterns on the value data or even key data and or more complex objects

I would assume there is a gem that does this well already

**Comment by clintoncwolfe** [comment]
Hrm... We already have a simple type verification system for inputs, allowing one to restrict to Numeric/String, etc. It looks like you want to be able to restrict to "the odd numbers" or "a particular JSON Schema" or even most generally a Proc. 

At that point, you might as well have an input plugin that examines its Event log and validates. Would the input API need to change for that?

**Comment by aaronlippold** [comment]
The idea that the user was asking for was the ability to match patterns of ip address or to validate that it *is* actually a pattern of ip address. Another that it was a 3 or 4 digit number. Etc.

**Comment by james-stocks** [comment]
That would be nice, so in `inspec.yml` I can declare:

```
- name: API_KEY
   type: string
   description: API key to connect to the API under test
   pattern: ^[0-9A-Fa-f]{15}$  
```

?

**Comment by clintoncwolfe** [comment]
So... just regex matches?

**Comment by aaronlippold** [comment]
With that example, https://github.com/inspec/inspec/issues/4229 comes back up. API keys password etc should be something we obscure in reporter and formatter output. I think if we could close the loop on valid pattern and then mark them sensitive our output itself doesn’t become confidential itself.  

On phase two we could also connect the two so that we identify parrerns we know would be protected automatically. 

Password, api key etc are great examples.

**Comment by aaronlippold** [comment]
Regex is a great start.  Let’s do that first and see what use cases that drives.

**Comment by Schwad** [comment]
Could those be two separate elements?
i.e. From Stocksy's above:

```yaml
- name: API_KEY
   type: string
   description: API key to connect to the API under test
   pattern: ^[0-9A-Fa-f]{15}$  
   confidential: true # defaults false
```

Or is there the need for actually checking the data formation as it hits the input to determine suppression?

i.e.

```yaml
- name: SOME_INPUT
   type: string
   description: API key to connect to the API under test
   pattern: ^[0-9A-Fa-f]{15}$  
   suppress_if_match: ^my_regex$ # Supply a matching pattern that causes suppression only if it matches
```
