### ISSUE TITLE
Inheriting local TAR file for a relative path in windows - inspec.yaml

### ISSUE THREAD

**Issue by Sum123it** [inspec/inspec#5048]
I need to inherit a local tarball for inspec.yml

# Describe the problem
I am trying to work with inspec-azure tar from github. but getting 443 connection timeout . Tried setting up git proxies - but no help. How to inherit .tar.gz locally?

**getting error for below yml file - path doesn't exist:**

```
version: 0.1.0
inspec_version: '4.18.111'
depends:
  - name: inspec-azure
    url: https://github.com/inspec/inspec-azure/archive/v1.14.2.tar.gz
    #path: '.\inspec-azure-1.14.2.tar.gz'
supports:
 # - platform: os
  - platform: azure
```

I need to get the **relative path** have a local tar.gz which I can use.
below works

```
 - name: inspec-azure
    #url: https://github.com/inspec/inspec-azure/archive/v1.14.2.tar.gz
    path: 'C:\Sumit\Azure\inspec_framework\inspec-profile\inspec-azure-1.14.2.tar.gz'
