### ISSUE TITLE
Additional aarch64 distros could be supported if not for a dependency on an old unv_ext (0.0.7.2)

### ISSUE THREAD

**Issue by snapp** [inspec/inspec#5058]
We're missing out an several distributions due to a transitive dependency.

# Describe the problem

Adding the following builder/tester mapping to `.expeditor/release.omnibus.yml` ([as done in this PR](https://github.com/inspec/inspec/pull/4981)) fails only due to a nested dependency on `unv_ext 0.0.7.2`:

```
  debian-10-aarch64:
    - debian-10-aarch64
  sles-15-aarch64:
    - sles-15-aarch64
  ubuntu-18.04-aarch64:
    - ubuntu-18.04-aarch64
    - ubuntu-20.04-aarch64
```

## Possible Solution
By forcing `unf_ext ~> 0.0.7.6` (https://github.com/inspec/inspec/commit/e3e68d5fe1f7948e91069587317479cb485374b9) we get successful builds but the `run-tests-ruby-2.7` step in the verify pipeline [fails](https://buildkite.com/chef-oss/inspec-inspec-master-verify/builds/1809#c6730fa3-e0dc-43a0-8b84-542278a75986) due to `train` resolving to `3.1.8` when `3.2.28` is required as explained by @james-stocks [in this comment](https://github.com/inspec/inspec/pull/4981#issuecomment-622435624)
