### ISSUE TITLE
Add support for `default_transport` specified in `inspec.yml`

### ISSUE THREAD

**Issue by skpaterson** [inspec/inspec#5141]
For the consumption of cloud and other InSpec profiles it is required add a dependency to the relevant resource pack e.g.
```
depends:
  - name: inspec-aws
    url: https://github.com/inspec/inspec-aws/archive/master.tar.gz
supports:
  - platform: aws
```
This effectively polarises the underlying transport choice e.g. `-t aws://` but we still surface that unnecessarily to the user when running InSpec.  

One possible solution would be to add a field to the resource pack `inspec.yml` files to specify the default transport e.g. 
```
default_transport: aws
```
This would allow downstream profiles to pick up the default transport setting and then optionally run `inspec exec` without the `-t aws://`.

Aha! Link: https://chef.aha.io/features/SH-2586
