### ISSUE TITLE
Inspec YML and Azure resources - Inspec is skipping my 'inspec-azure' profile

### ISSUE THREAD

**Issue by rohancollab** [inspec/inspec#5146]
I am not sure if I am including inspec azure resources correctly in my inspec-yml. So when I run my inspec tests in a docker container using gitlab-ci.yml, it fails because 'inspec-azure' profile is skipped while inspec runs the tests - 

Here is my inspec-yml

```yaml
name: my-profile
title: My own Azure profile
version: 1.0.0
depends:
    - name: inspec-azure
      git: https://github.com/inspec/inspec-azure.git
      supports:
       - platform-name: debian
```
here are my pipeline failures when I try to run the Inspec Azure tests 

$ inspec exec "Inspec-AzureTests"
[2020-07-17T03:18:58+00:00] WARN: Skipping profile: 'inspec-azure' on unsupported platform: 'debian/10.4'.
Profile: My own Azure profile (my-profile)
Version: 1.0.0
Target:  local://
  ×  azure-webapp-verification: Inspec-AzureTests/controls/azure-verify.rb:1
     ×  Control Source Code Error Inspec-AzureTests/controls/azure-verify.rb:1 
     undefined method `azurerm_webapp' for #<Inspec::Rule:0x000055a6b7e21f18>
Profile Summary: 0 successful controls, 1 control failure, 0 controls skipped
Test Summary: 0 successful, 1 failure, 0 skipped
ERROR: Job failed: exit code 1

 Also tried using 'supports' in inspec.yml as below 
```yaml
name: my-profile
title: My own Azure profile
version: 1.0.0
depends:
    - name: inspec-azure
      git: https://github.com/inspec/inspec-azure.git
      supports:
       - platform-name: debian
supports:
     - platform-name: debian

```

Is there any other way to include the azure resources?

Aha! Link: https://chef.aha.io/features/SH-2624

**Comment by james-stocks** [comment]
Hi @rohancollab -

Using `inspec-azure` means that InSpec is targeting Azure. Declaring `supports` `debian` causes your profile to only work when targeting a Debian host. If you want to scan Azure you'll need to remove the `supports` `debian`.

If you have a need to run tests both against a Debian host and an Azure account, these need to be kept in separate profiles. One that supports `debian` and the other that loads `inspec-azure`

**Comment by rohancollab** [comment]
Thanks @james-stocks . That works! I wanted to test azure webapp from my debian host and earlier I had created one profile and was trying to import azure resource pack in this profile. 

For someone running into same issue, here's what worked for me.
Created a separate profile for Azure and included that in inspec tests as follows and it works

In Inspec-AzureTests directory

inspec.yml
```
name: inspec-profile
title: inspec-profile
version: 1.0.0
depends:
  - name: azure-profile
    path: Azure
```

In the Inspec-AzureTests/Azure directory
inspec.yml
```
name: azure-profile
title: My own Azure profile
version: 1.0.0
depends:
  - name: inspec-azure
    url: https://github.com/inspec/inspec-azure/archive/v1.18.1.tar.gz

```
