### ISSUE TITLE
Extend profile inheritance to support reuse of helper classes in downstream profiles

### ISSUE THREAD

**Issue by skpaterson** [inspec/inspec#5147]
A common pattern in cloud and other resource packs is to have a `backend` base-class that handles all the connection management and other reusable functionality shared between resources.  

Using AWS as an example, if a user creates a new profile and depends on a resource pack:
```
depends:
  - name: inspec-aws
    url: https://github.com/inspec/inspec-aws/archive/master.tar.gz
supports:
  - platform: aws
```
In the situation they want to create a new custom resource for this profile then they currently have to inherit from `Inspec.resource(1)` and cannot leverage the `backend` class in the parent profile (resource pack).  

Ideally they would want to be able to do e.g. 
```
MyNewResource < AwsResourceBase
```
For those contributing to a resource pack the typical pattern is to branch so this isn't a problem.  This only applies to custom resources in downstream profiles that want to also make use of parent resource pack backend classes.

Aha! Link: https://chef.aha.io/features/SH-2627
