### ISSUE TITLE
Iterating over inputs raises a "undefined method `each' for #<RSpec::Core::Example" error

### ISSUE THREAD

**Issue by rbclark** [inspec/inspec#5230]
Given the following codeblock:

```ruby
control 'V-XXXX' do
    describe firewalld do
      input('firewalld_hosts_deny').each do |rule|
        it { should_not have_rule_enabled(rule) }
      end
    end
end
```

and the following inspec.yml excerpt:

```yaml
- name: firewalld_hosts_deny
  description: "Hosts that firewalld should be configured to deny."
  type: Array
  value: []
```

#### Expected Behavior
I would expect the control to successfully run if the user specifies a list of denied hosts, and I would expect the block to be skipped by default if no values are provided. 

#### Actual Behavior
```
Failed to complete #verify action: [undefined method `each' for #<RSpec::Core::Example "firewalld_hosts_deny">]
```

This behavior is manifesting itself on both InSpec 4.18.114 & InSpec 4.22.1.

If I replace the codeblock with

```ruby
control 'V-XXXX' do
    firewalld_hosts_deny = input('firewalld_hosts_deny')
    describe firewalld do
      firewalld_hosts_deny.each do |rule|
        it { should_not have_rule_enabled(rule) }
      end
    end
end
```

everything runs successfully.
