### ISSUE TITLE
Pulling in vendor profiles from git fails when using the docker container

### ISSUE THREAD

**Issue by geogdog** [inspec/inspec#5416]
# Describe the problem
When running an `ssl_certificate` test using:
```
depends:
- name: ssl-certificate-profile
  git: https://github.com/alexpop/ssl-certificate-profile
  version: '~> 1.0'
```
inspec fails as there is no git installed to get it.

## Possible Solution
Add git to the list of packages installed within the container.
