### ISSUE TITLE
Dependencies between monorepos

### ISSUE THREAD

**Issue by micheelengronne** [inspec/inspec#5451]
# Describe the problem

I have a monorepo `monorepoA` that has the following structure:

````
profiles:
  - profileA
  - profileB
README
````

`profileB` depends of `profileA` and I use this syntax:

````
depends:
  - name: profilea
    path: ../profileA
````

I have another repo `monorepoB` that has a profile (`profileC`) in it that depends of profileB. I use this syntax:

````
depends:
  - name: profileb
    git: https://example.com/test/monorepoA.git
    tag: 1.0.0
    relative_path: profiles/profileB
````

`profileC` fetch correctly `profileB` but it breaks when fetching `profileA` (dependency of `profileB`). The fetcher looks for a `profileA` in the same directory as `profileC` (instead of `profileB`).

I would like to be able to constrain relative paths inside the monorepo scope. In other words, I would like the possibility to still use the syntax between `profileB` and `profileA` without problems with subsequent dependencies.

## Possible Solution
Currently, I uses the syntax between `profileC` and `profileB` everywhere, so the monorepo path is not taken into account.
