### ISSUE TITLE
Error "Cannot load such file -- aws-sdk-ecrpublic (LoadError)" while trying to run Inspec profile against AWS resource pack

### ISSUE THREAD

**Issue by Aniket281292** [inspec/inspec#5494]
Error "cannot load such file -- aws-sdk-ecrpublic (LoadError)" encountered while trying to run an inspec profile to test against aws resources.
# Describe the problem

I have a inspec profile called as "aws-test" and couple of inspec tests(ekstest.rb abctest.rb) in controls folder. When i try to run those inspec tests by mentioning the test names in the command, i am able to execute these tests successfully and dont see any error. Commands used to execute these tests:
inspec exec ~/.../aws-test/controls/ekstest.rb -t aws://us-east-1
inspec exec ~/.../aws-test/controls/abctest.rb -t aws://us-east-1.

However when i am trying to run inspec profile by mentioning the profile name, i am seeing the following error:
**command**: inspec exec aws-test -t aws://us-east-1

Error: 
1: from /opt/inspec/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
/opt/inspec/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- aws-sdk-ecrpublic (LoadError)

**Comment by r-goto** [comment]
Had the same issue but the following inspec.yml fixed it in my case. 

```
---
name: my-profile
title: AWS InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile For AWS
version: 0.1.0
inspec_version: '>= 4.6.9'
depends:
  - name: inspec-aws
    url: https://github.com/inspec/inspec-aws/archive/1.0.1-for-inspec-4.7.tar.gz
supports:
  - platform: aws
```

`url: https://github.com/inspec/inspec-aws/archive/1.0.1-for-inspec-4.7.tar.gz` did it, I believe.
