### ISSUE TITLE
Can't get sub key in YAML

### ISSUE THREAD

**Issue by scalp42** [inspec/inspec#554]
Assuming this YAML:

```
root@master-ubuntu-1404:~# cat /opt/singularity/singularity_config.yaml

---
enableCorsFilter: true
sandboxDefaultsToTaskId: false
server:
  type: simple
  applicationContextPath: "/"
  connector:
    type: http
    port: 8070
  requestLog:
    appenders:
    - type: file
      currentLogFilename: "/var/log/singularity-access.log"
      archivedLogFilenamePattern: "/var/log/singularity-access-%d.log.gz"
mesos:
  master: zk://192.168.99.100:2181/mesos
  defaultCpus: 0.1
  defaultMemory: '128'
  frameworkName: Singularity
  frameworkId: Singularity
  frameworkFailoverTimeout: 1000000
```

Here is the spec:

``` ruby
describe yaml('/opt/singularity/singularity_config.yaml') do
  its('mesos.master') { should eq "zk://#{node['normal']['boot2docker']}:2181/mesos" }
end
```

I'm getting the following error:

```
Failures:

  1) YAML /opt/singularity/singularity_config.yaml mesos.master
     Failure/Error: inner_subject.send(attr)

     NoMethodError:
       undefined method `master' for #<Hash:0x007fc2031ca670>
     # ./test/integration/master/inspec/singularity_spec.rb:40:in `block (2 levels) in load'
     # /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/inspec-0.14.8/lib/inspec/runner_rspec.rb:55:in `run'
     # /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/kitchen-inspec-0.12.3/lib/kitchen/verifier/inspec.rb:73:in `call'
     # /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:423:in `block in verify_action'
     # /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:513:in `call'
     # /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:513:in `synchronize_or_call'
     # /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:478:in `block in action'
     # /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:477:in `action'
     # /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:415:in `verify_action'
     # /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:348:in `block in transition_to'
     # /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:347:in `each'
     # /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:347:in `transition_to'
     # /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:160:in `verify'
     # /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/test-kitchen-1.6.0/lib/kitchen/command.rb:176:in `public_send'
     # /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/test-kitchen-1.6.0/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'

Finished in 2.55 seconds (files took 0.55058 seconds to load)
194 examples, 1 failure
```

Any idea how to access `['mesos']['master']` ?
