### ISSUE TITLE
undefined method `addresses' for Port

### ISSUE THREAD

**Issue by scalp42** [inspec/inspec#555]
Assuming a java app listening on port `8090`:

``` ruby
describe port(8090) do
  it { should be_listening }
  its('processes') {should include 'java'}
  its('protocols') { should eq ['tcp6'] }
  its('addresses') {should include '0.0.0.0'}
end
```

I'm getting the following error:

```
Failures:

  1) Port  8090 addresses
     Failure/Error: inner_subject.send(attr)

     NoMethodError:
       undefined method `addresses' for Port  8090:#<Class:0x007fc3662a5248>
     # ./test/integration/master/inspec/chronos_spec.rb:60:in `block (2 levels) in load'
     # /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/inspec-0.14.8/lib/inspec/runner_rspec.rb:55:in `run'
     # /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/kitchen-inspec-0.12.3/lib/kitchen/verifier/inspec.rb:73:in `call'
     # /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:423:in `block in verify_action'
     # /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:513:in `call'
     # /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:513:in `synchronize_or_call'
     # /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:478:in `block in action'
     # /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:477:in `action'
     # /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:415:in `verify_action'
     # /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:348:in `block in transition_to'
     # /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:347:in `each'
     # /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:347:in `transition_to'
     # /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:160:in `verify'
     # /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/test-kitchen-1.6.0/lib/kitchen/command.rb:176:in `public_send'
     # /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/test-kitchen-1.6.0/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'

Finished in 2.47 seconds (files took 0.50982 seconds to load)
199 examples, 1 failure
```

I can get around it by using `netcat` or something but figured should open an issue :innocent:
