### ISSUE TITLE
Unable to override dependent profile input using DSL

### ISSUE THREAD

**Issue by TypeMayVary** [inspec/inspec#5658]
# Describe the problem

I have set an input in the inspec.yml file of Profile B (dependency on Profile A):
```YAML
name: profile-b
## other metadata
inputs:
- name: dependent-input
  required: true
```
I have profile A which has a dependency on Profile B
```YAML
name: profile-a
## other metadata
depends:
  - name: profile-b
    path: path/to/profile/b
```

Expectation:
When I set the input, using the profile option, in a control file like so:
```ruby
input('dependent-input', value: 'this-value-is-set', profile: 'profile-b', priority: 50)
```
The input should be set for controls in profile B when I execute profile A

Actual result:
When Profile A is executed
```bash
$ inspec exec profile-a .......
Input 'dependent-input' is required and does not have a value.
```

**Comment by Vasu1105** [comment]
This issue occurs in case you have not set the value in the DSL in the dependent profile. Setting value in both the profile is required as you are using required: true. Please let me know if this resolves your problem.

I tried to reproduce the same error by the following the example

I have 2 profiles `profile-a` and `profile-b`

`profile-a` depends on `profile-b`

profile-a inspec.yml

```
depends:
- name: profile-b
  path: ../profile-b
```

profile-b inspec.yml
```
inputs:
- name: my_fav_food
  required: true
```

profile-a controls/example.rb file
```
include_controls "profile-b"

input('my_fav_food', value: 'orange', priority: 50)

control "profile-a faviourte food" do
  describe input('my_fav_food') do
    it { should cmp 'orange' }
  end
end
```
profile-b controls/example.rb file
```
control "profile-b faviourte food" do
  describe input('my_fav_food') do
    it { should cmp 'banana' }
  end
end
```

if I run `nspec exec` with the above settings then I do come across the same issue, which I guess is the expected behavior as I don't have the required input set for profile-b. When I did the following changes in profile-b I am not coming across the mentioned issue.

```
input('my_fav_food', value: 'banana', priority: 20)

control "profile-b faviourte food" do
   describe input('my_fav_food') do
     it { should cmp 'banana' }
   end
end
```

I hope that resolves your issue @TypeMayVary

**Comment by TypeMayVary** [comment]
Hi @Vasu1105,
From your suggestion, it seems that you cannot set the input of a different profile from another profile. So my use case would be that I want to be able to set an input of `profile-b` from `profile-a` and run `profile-b`'s controls using the input I set in `profile-a`, and setting an `include_controls 'profile-b'` in `profile-a`.

Is this something that is possible?

**Comment by Vasu1105** [comment]
I don't think the override is meant to work like that as per the docs https://docs.chef.io/inspec/inputs/#using-inputs-with-profile-inheritance

**Comment by Vasu1105** [comment]
@TypeMayVary You can set values for other dependent profiles in the parent profile in the metadata file i.e. inspec.yml file. Use the profile option to specify that. on DSL level that is not supported.
Setting following in the inspec.yml of parent profile workes
```
depends:
- name: profile-b
  path: ../profile-b
- name: profile-c
  path: ../profile-c
inputs:
- name: my_fav_food
  value: "banana"
  priority: 30
  profile: profile-b
- name: my_fav_food
  value: "orange"
  priority: 30
- name: your_fav_food
  value: "banana"
  priority: 30
  profile: profile-c
```
Docs https://docs.chef.io/inspec/inputs/#simple-precedence
