### ISSUE TITLE
include_waiver is not recognized

### ISSUE THREAD

**Issue by jtonello** [inspec/inspec#5720]
A simple recipe I have uses both `include_profile` and `include_waiver`, but the waiver is not recognized and is not applied.

# Describe the problem
I've created the following simple `control-waiver.yml` file to alternately turn on and off two InSpec controls:
```
nginx-config:
  expiration_date: 2022-12-31
  run: true
  justification: "This control is waived for testing purposes."

nginx-security:
  expiration_date: 2022-12-31
  run: false
  justification: "This control is waived for testing purposes."
```
My recipes/default.rb looks like this:
```
include_profile 'nginx::nginx'
include_waiver 'nginx::.*'
include_recipe 'nginx::webserver
```
Testing this waiver using `inspec exec compliance/profiles/nginx/ --waiver-file compliance/waivers/control-waiver.yml` successfully waives the control in the CLI output on my local machine running Workstation. However, when running `chef-client` on the node after updating my Policyfile.rb (`chef update Policyfile.rb`) and pushing it (`chef push prod Policyfile.lock.json`), neither the node nor Automate are aware of the waiver.
