### ISSUE TITLE
`require': cannot load such file -- aws-sdk-waf (LoadError)

### ISSUE THREAD

**Issue by ABlasakis** [inspec/inspec#5747]
Hello,

I have a  the error `require': cannot load such file -- aws-sdk-waf (LoadError)

When I run the following command:
`inspec exec tests --no-create-lockfile -t aws://ca-central-1`

I have as configuration : 
```yaml
inspec_version: ">= 4.50"
depends:
- name: inspec-aws
  git: https://github.com/inspec/inspec-aws.git
  version: ~> 1.74.72
supports:
  platform: aws
```

I run inspec on a version with the :
`inspec -v`
4.50.3

I have the version of ruby:
`ruby -v`
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-darwin20]

Do you know what might be missing in my configuration ? I must be missing something.
