### ISSUE TITLE
kitchen-inspec error when verifying concurrencly: Train::Transports::SSH does not implement #connect()

### ISSUE THREAD

**Issue by rndmh3ro** [inspec/inspec#577]
When running the verify-step on hosts sequentially, it works:

```
basti ~/os-hardening/ansible-ssh-hardening $  bundle exec kitchen verify ubuntu-1204
-----> Starting Kitchen (v1.6.0)
-----> Verifying <default-ubuntu-1204>...
       Detected alternative framework tests for `inspec`
       Search `/home/basti/os-hardening/ansible-ssh-hardening/test/integration/default/inspec` for tests
...............................................................................................

Finished in 0.36432 seconds (files took 0.74597 seconds to load)
95 examples, 0 failures

       Finished verifying <default-ubuntu-1204> (0m1.03s).
-----> Kitchen is finished. (0m1.27s)
zlib(finalizer): the stream was freed prematurely.
basti ~/os-hardening/ansible-ssh-hardening $  bundle exec kitchen verify ubuntu-1404
-----> Starting Kitchen (v1.6.0)
-----> Verifying <default-ubuntu-1404>...
       Detected alternative framework tests for `inspec`
       Search `/home/basti/os-hardening/ansible-ssh-hardening/test/integration/default/inspec` for tests
^[[A...............................................................................................

Finished in 0.37396 seconds (files took 0.74711 seconds to load)
95 examples, 0 failures

       Finished verifying <default-ubuntu-1404> (0m1.04s).
-----> Kitchen is finished. (0m1.27s)
zlib(finalizer): the stream was freed prematurely.

```

But when running verify on multiple hosts in parallel, the following error occurs:

```
basti ~/os-hardening/ansible-ssh-hardening $  bundle exec kitchen verify ubuntu -c
-----> Starting Kitchen (v1.6.0)
-----> Verifying <default-ubuntu-1204>...
-----> Verifying <default-ubuntu-1404>...
       Detected alternative framework tests for `inspec`
       Detected alternative framework tests for `inspec`
       Search `/home/basti/os-hardening/ansible-ssh-hardening/test/integration/default/inspec` for tests
       Search `/home/basti/os-hardening/ansible-ssh-hardening/test/integration/default/inspec` for tests
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #verify action: [Train::Transports::SSH does not implement #connect()]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

```

inspec version:

```
basti ~/os-hardening/ansible-ssh-hardening $  bundle show kitchen-inspec
/usr/lib/ruby/gems/2.3.0/gems/kitchen-inspec-0.12.5
```

`.kitchen.yml`:

```

---
driver:
  name: vagrant
provisioner:
  name: ansible_playbook
  test_repo_uri: https://github.com/hardening-io/tests-ssh-hardening.git
  hosts: all
  require_ansible_repo: false
  require_ansible_omnibus: true
  require_chef_for_busser: false
  require_ruby_for_busser: false
platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box
- name: ubuntu-14.04
  driver_config:
    box: opscode-ubuntu-14.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
- name: centos-6.5
  driver_config:
    box: opscode-centos-6.5
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box
- name: oracle-6.4
  driver_config:
    box: oracle-6.4
    box_url: https://storage.us2.oraclecloud.com/v1/istoilis-istoilis/vagrant/oel64-64.box
- name: oracle-6.5
  driver_config:
    box: oracle-6.5
    box_url: https://storage.us2.oraclecloud.com/v1/istoilis-istoilis/vagrant/oel65-64.box
- name: debian-7
  driver_config:
    box: debian-7
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-7.8_chef-provisionerless.box
- name: debian-8
  driver_config:
    box: debian-8
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-8.1_chef-provisionerless.box
verifier:
  name: inspec
suites:
- name: default
  hosts: all
  ansible_verbose: true
  ansible_diff: true
  roles_path: ../ansible-ssh-hardening/
  provisioner:
    playbook: test/integration/playbooks/default.yml
```
