### ISSUE TITLE
passing a json file to profile input as a value 

### ISSUE THREAD

**Issue by tonyvilliams** [inspec/inspec#5925]
How do we pass an entire file as an input to a profile input. 

**scenario**:  
I have inspec profile-A(10 controls), Profile-B(15 controls), Profile-C(5 controls) Profile-A depends on Profile-B and Profile-C. I have a file in Profile-A which I am prasing with inspec.profile.file('test.json') and executing the 10 controls in the same profile. I have to pass the same file to Profile-B and Profile-C so that I can execute the other set of tests in each profile as part of the profile dependency I am able to successfully parse the test.json file in profile-A as the file is in correct folder path
```
myjson = json(content: inspec.profile.file('test.json'))
puts myjson 
```
I have followed the inspec documentation to set up the profile dependency and inputs to the dependant profiles. https://docs.chef.io/inspec/inputs/

**Issue**: Issue is that I am able to pass a single Input values (like string, array etc..) to the dependent profiles but not able to pass the entire json file so that it will parse and the controls will be executed.

I have tried the following in the profile metadata file
```
# ProfileB inspec.yml
name: profile-b
inputs:
- name: file1
- name: file2
```

```
# wrapper inspec.yml
name: profile-A
depends:
- name: profile-b
  path: ../profile-b
inputs:
- name: file1
  value: 'json(content: inspec.profile.file('test.json'))'
  profile: profile-b 
- name: file2
  value: 'FILE.read('/path/to/test.json')'
  profile: profile-b 
```

**Error**: when I try to load the file1, file2 in profile-b with the following
```
jsonfile1 = input('file1')
jsonfile2 = input('file2')

puts jsonfile1
puts jsonfile2
```

error - no implicit conversion of nil to integer

**Goal**:

I should be able to pass the file from profile-A to profile-B or profile-C so that the respective dependent profile controls are execute.
