### ISSUE TITLE
inspec cli output unclear when same resource pack is used in different versions by dependencies

### ISSUE THREAD

**Issue by tbugfinder** [inspec/inspec#5978]
# Describe the problem

I'm using inspec-aws as a dependency within the "base" control in e.g. version 1.80.
The "base" controls also depends on another (git-hosted) my2nd-profile which again depends on inspec-aws however in this case a different version, e.g. 1.30.
The output of inspec executes all controls (base and my2nd) however the output only shows inspec-aws profile in version 1.30.
Inspec.lock file includes both versions of inspec-aws.
So I'm assuming that inspec pulls in the respective version when needed however the output only lists one version ( the last in sequence).

## Possible Solution

Ooutput both profile versions even if the profile (resource pack) name is not unique but the same.

**Comment by tbugfinder** [comment]
Configuration:

Create two profiles from scratch and add a dependency to inspec-aws using different versions:
```
$ cat profiles/profile*/inspec.yml 
name: profile1
title: AWS InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile For AWS
version: 0.1.0
inspec_version: '~> 4'
depends:
  - name: inspec-aws
    git: https://github.com/inspec/inspec-aws
    tag: v1.31.0
supports:
  - platform: aws


name: profile2
title: AWS InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile For AWS
version: 0.1.0
inspec_version: '~> 4'
depends:
  - name: inspec-aws
    git: https://github.com/inspec/inspec-aws
    tag: v1.79.0
supports:
  - platform: aws
```


Integrate it into root / base profile:

```
 cat test/integration/default/inspec.yml 
name: profile1
title: AWS InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile For AWS
version: 0.1.0
inspec_version: '~> 4'
depends:
  - name: profile1
    path: ../../../profiles/profile1
  - name: profile2
    path: ../../../profiles/profile2
supports:
  - platform: aws

```



Output when executing inspec ==> there's only a single inspec-aws profile version printed.
```
$ bundle exec inspec exec test/integration/default/ --target aws://
[2022-04-12T23:28:06+02:00] WARN: Input 'aws_vpc_id' does not have a value. Use --input-file or --input to provide a value for 'aws_vpc_id' or specify a  value with `input('aws_vpc_id', value: 'somevalue', ...)`.
[2022-04-12T23:28:54+02:00] WARN: Input 'aws_vpc_id' does not have a value. Use --input-file or --input to provide a value for 'aws_vpc_id' or specify a  value with `input('aws_vpc_id', value: 'somevalue', ...)`.
[2022-04-12T23:29:07+02:00] WARN: Input 'aws_vpc_id' does not have a value. Use --input-file or --input to provide a value for 'aws_vpc_id' or specify a  value with `input('aws_vpc_id', value: 'somevalue', ...)`.
[2022-04-12T23:29:07+02:00] WARN: Input 'aws_vpc_id' does not have a value. Use --input-file or --input to provide a value for 'aws_vpc_id' or specify a  value with `input('aws_vpc_id', value: 'somevalue', ...)`.
[2022-04-12T23:29:07+02:00] WARN: Input 'aws_vpc_id' does not have a value. Use --input-file or --input to provide a value for 'aws_vpc_id' or specify a  value with `input('aws_vpc_id', value: 'somevalue', ...)`.

Profile: AWS InSpec Profile (profile1)
Version: 0.1.0
Target:  aws://

     No tests executed.

Profile: AWS InSpec Profile (profile1)
Version: 0.1.0
Target:  aws://

     No tests executed.

Profile: Amazon Web Services  Resource Pack (inspec-aws)
Version: 1.79.0    <<<<<<<<<<<<<<<<<<<<<<<<<===================== there's only a single dependency version listed.
Target:  aws://

     No tests executed.

Profile: AWS InSpec Profile (profile2)
Version: 0.1.0
Target:  aws://

     No tests executed.

Test Summary: 0 successful, 0 failures, 0 skipped

```

**Comment by tbugfinder** [comment]
content of inspec.lock shows both inspec-aws profiles:
```
$ cat  test/integration/default/inspec.lock 
---
lockfile_version: 1
depends:
- name: profile1
  resolved_source:
    path: "/home/parallels/GITHUB/kttfsample/profiles/profile1"
  version_constraints: []
  dependencies:
  - name: inspec-aws
    resolved_source:
      git: https://github.com/inspec/inspec-aws
      ref: e2425f88b2adb01c3f640086422f2599b159d0c3
    version_constraints: []
- name: profile2
  resolved_source:
    path: "/home/parallels/GITHUB/kttfsample/profiles/profile2"
  version_constraints: []
  dependencies:
  - name: inspec-aws
    resolved_source:
      git: https://github.com/inspec/inspec-aws
      ref: c860ec0b950b4f84cfce288ae1bb9d8fb0794450
    version_constraints: []

```

**Comment by Nik08** [comment]
@tbugfinder I was devising solution for this. And because of failures in the solution, it occurs to me that the simplest thing to solve this would be to use unique names. Because if the names are not unique, and if you intend to include controls from a profile of a specific version, you will not be able to do that. And just having unique names will solve this.
Also this is like an edge case. 
Let me know your thoughts on this. Thanks!

**Comment by tbugfinder** [comment]
Well, inspec supports stacking profiles utilizing include_controls statement(s). As a user I cannot override or influence the profile names and versions such included profiles depend on. As a consequence of having include_controls (and chained dependencies) feature, listing names and versions should be distinct.

**Comment by Nik08** [comment]
@tbugfinder Hey just need one clarification, are you saying that since your profile dependency is on [inspec-aws](https://github.com/inspec/inspec-aws) that is why as a user you are required to use name as `inspec-aws`?

I want to clarify, you can use this profile in your dependency and still use different name for the same url.

You settings could be:
```
name: profile1
title: AWS InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile For AWS
version: 0.1.0
inspec_version: '~> 4'
depends:
  - name: inspec-aws-v131
    git: https://github.com/inspec/inspec-aws
    tag: v1.31.0
supports:
  - platform: aws


name: profile2
title: AWS InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile For AWS
version: 0.1.0
inspec_version: '~> 4'
depends:
  - name: inspec-aws-v179
    git: https://github.com/inspec/inspec-aws
    tag: v1.79.0
supports:
  - platform: aws
```

Different naming to same url is allowed. Please help me understand if you are confused about this.
Thanks

**Comment by tbugfinder** [comment]
It's well understood that the profile name can be set to whatever is preferred or derive its name based on the original name and the version being used to make it kind of unique.
However I wouldn't consider this as an approach which really works for us due to various maintenance reasons.

Currently we have ~80 profiles utilizing inspec-* resource packs utilizing only a few versions.
Having above approach we'd have to touch all profiles and add a distinct dependency name based on name and version.

From time to time we'd also like to bump versions of inspec-* resource packs which is basically a git merge upstream process.

**Comment by Nik08** [comment]
I feel this issue does not require any fixing, I will explain why. So I did some playing around with similar scenarios. 

I tried a scenario of pointing my profiles to the same profile with same name and it is a local profile unlike a git profile ( without any version )

Details of those profiles are as follows:

Dependency goes like this: 

**Test-parent -> ( test-child-1 & test-child-2 ) -> test-child-3**

Metadata file of parent profile ( test-parent )
```
name: test-parent
title: InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile
version: 0.1.0
supports:
  platform: os
depends:
  - name: test-child-1
    path: ../test-child-1
  - name: test-child-2
    path: ../test-child-2
```

Metadata file for test-child-1

```
name: test-child-1
title: InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile
version: 0.1.0
supports:
  platform: os
depends:
  - name: test-child-3
    path: ../test-child-3
```

Metadata file for test-child-2

```
name: test-child-2
title: InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile
version: 0.1.0
supports:
  platform: os
depends:
  - name: test-child-3
    path: ../test-child-3
```

Then I ran parent profile ( test-parent ), and I got output like

```
Profile:   InSpec Profile (test-parent)
Version:   0.1.0
Target:    local://
Target ID: fa3923b9-f806-4cc2-960d-1ddefb4c7654

  ✔  tmp-1.0: Create /tmp directory
     ✔  File /tmp is expected to be directory

  File /tmp
     ✔  is expected to be directory

Profile:   InSpec Profile (test-child-1)
Version:   0.1.0
Target:    local://
Target ID: fa3923b9-f806-4cc2-960d-1ddefb4c7654

     No tests executed.

Profile:   InSpec Profile (test-child-3)
Version:   0.1.0
Target:    local://
Target ID: fa3923b9-f806-4cc2-960d-1ddefb4c7654

     No tests executed.

Profile:   InSpec Profile (test-child-2)
Version:   0.1.0
Target:    local://
Target ID: fa3923b9-f806-4cc2-960d-1ddefb4c7654

     No tests executed.
```

The reason why it ran `test-child-3` only once is because both `test-child-1` and `test-child-2` are using same profile with same name. And  **test-child-2** overrides  **test-child-1** and only execute it once. So this is the behaviour of inspec if you are using same profile **(irrespective of version)**. And it identifies same profile using it's name. 

So if you change the **naming** like I suggested earlier, it will not be beneficial either because it will run similar test cases twice in the end and it is not the best approach in this case. It overrides so that it can only run same profile and tests once (In your scenario, you are using same profile and overriding version 1.31 with version 1.79 ). So since it is running the updated version (1.79.0) and not (1.31.0), this seems like the right thing to happen here.
