### ISSUE TITLE
`sensitive: true` does not obfuscate inputs in overlays

### ISSUE THREAD

**Issue by karikarshivani** [inspec/inspec#6009]
Inputs with `sensitive: true` at the baseline profile level are hidden from the viewer, however, an overlay that depends on that baseline profile does not hide the same inputs.

# Describe the problem

The [inspec.yml](https://github.com/mitre/microsoft-sql-server-2017-cis-baseline/blob/v1.2.0/inspec.yml) file in the baseline has certain inputs marked as sensitive that are properly hidden from the user. [The overlay](https://github.com/mitre/aws-rds-microsoft-sql-server-2017-cis-baseline/tree/v1.2.0) does not hide the same inputs pulled from the baseline unless I add them to the overlay inspec.yml file. Screenshots of the baseline output and the overlay output below:

_Baseline hides sensitive inputs (as expected)_
![Baseline](https://user-images.githubusercontent.com/11844975/164772634-82f7c4e3-c112-4bf6-a94c-8aafafab2627.png)

_Overlay does not hide sensitive inputs when there is no `inputs` section_
![Overlay](https://user-images.githubusercontent.com/11844975/164772645-b799e193-340d-4026-bb3a-74fdf333b727.png)

## Possible Solution

As a temporary solution, we've duplicated the sensitive baseline inputs in the `inspec.yml` file of the overlay. That seems to hide the sensitive inputs from the viewer, however, we usually add inputs to an overlay only when they need to be overridden.

**Comment by karikarshivani** [comment]
Related #5404

**Comment by karikarshivani** [comment]
### Update:
The **Possible Solution** I mentioned above only obfuscates inputs in an overlay when the `profile: <profile-name>` option is not used. We usually use the [profile option to override input values](https://docs.chef.io/inspec/inputs/#using-inputs-with-profile-inheritance) if there are default values listed in the baseline.
This makes the temporary solution we listed less effective as we have more limitations now. We have to choose between overriding input values and making them sensitive.

**Comment by Vasu1105** [comment]
@kekaichinose could you please post here the example of your dependent profiles. This will help us reproduce the issue. Currently, we tried the following example which obfuscates the inputs in JSON reporter in both the cases.

profile_with_sensitive input

example.rb
```
control "read-an-explicitly-nonsesnitve-input" do
  describe input("sensitive-input") do
    it { should eq "test123" }
  end
end
```
inputs.yml
```
name: sensitive-input
title: InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile
version: 0.1.0
supports:
  platform: os
inputs:
  - name: sensitive-input
    value: test123
    sensitive: true
```

profile example which is dependent on above 

example.rb
```
title "sample section"

include_controls "sensitive-input"

control "read-an-explicitly-nonsesnitve-input-data" do
  describe input("sensitive-input") do
    it { should eq "test1234" }
  end
end
```
inspec.yml
```
name: depends-on-sensitive
title: InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile
version: 0.1.0
supports:
  platform: os
depends:
  - name: sensitive-input
    path: ../sensitive-input
inputs:
  - name: sensitive-input
    value: test1234
    sensitive: true
```

output of the `inspec exec depends-on-sensitive --no-create-lockfile --reporter json`

```
{"platform":{"name":"mac_os_x","release":"21.3.0","target_id":"0744915e-9ac4-5993-a769-a7cf9db10a72"},"profiles":[{"name":"depends-on-sensitive","version":"0.1.0","sha256":"a8588fd3acfab5cb8252b843b8702cc3f077454f9bcb3874bbd3f6e019c3cc1c","title":"InSpec Profile","maintainer":"The Authors","summary":"An InSpec Compliance Profile","license":"Apache-2.0","copyright":"The Authors","copyright_email":"you@example.com","supports":[{"platform":"os"}],"attributes":[{"name":"sensitive-input","options":{"value":"***","sensitive":true}}],"depends":[{"name":"sensitive-input","path":"../sensitive-input","status":"loaded"}],"groups":[{"id":"controls/example.rb","controls":["read-an-explicitly-nonsesnitve-input-data"],"title":"sample section"},{"id":"/Users/vjagdale/workspace/test-profiles/sensitive-input/controls/example.rb","controls":["read-an-explicitly-nonsesnitve-input"]}],"controls":[{"id":"read-an-explicitly-nonsesnitve-input","title":null,"desc":null,"descriptions":[],"impact":0.5,"refs":[],"tags":{},"code":"control \"read-an-explicitly-nonsesnitve-input\" do\n  describe input(\"sensitive-input\") do\n    it { should eq \"test123\" }\n  end\nend\n","source_location":{"line":1,"ref":"/Users/vjagdale/workspace/test-profiles/sensitive-input/controls/example.rb"},"waiver_data":{},"results":[]},{"id":"read-an-explicitly-nonsesnitve-input-data","title":null,"desc":null,"descriptions":[],"impact":0.5,"refs":[],"tags":{},"code":"control \"read-an-explicitly-nonsesnitve-input-data\" do\n  describe input(\"sensitive-input\") do\n    it { should eq \"test1234\" }\n  end\nend\n","source_location":{"line":7,"ref":"/Users/vjagdale/workspace/test-profiles/depends-on-sensitive/controls/example.rb"},"waiver_data":{},"results":[{"status":"passed","code_desc":"test1234 is expected to eq \"test1234\"","run_time":0.00116,"start_time":"2022-05-16T17:02:22+05:30","resource_class":"Object","resource_params":"[]","resource_id":"test1234"}]}],"status":"loaded","status_message":""},{"name":"sensitive-input","version":"0.1.0","sha256":"a85620a0b982e8521d38064955368916f65d1c92652abc7b33fa3174f33002a1","title":"InSpec Profile","maintainer":"The Authors","summary":"An InSpec Compliance Profile","license":"Apache-2.0","copyright":"The Authors","copyright_email":"you@example.com","supports":[{"platform":"os"}],"attributes":[{"name":"sensitive-input","options":{"value":"***","sensitive":true}}],"parent_profile":"depends-on-sensitive","groups":[{"id":"controls/example.rb","controls":["read-an-explicitly-nonsesnitve-input"]}],"controls":[{"id":"read-an-explicitly-nonsesnitve-input","title":null,"desc":null,"descriptions":[],"impact":0.5,"refs":[],"tags":{},"code":"control \"read-an-explicitly-nonsesnitve-input\" do\n  describe input(\"sensitive-input\") do\n    it { should eq \"test123\" }\n  end\nend\n","source_location":{"line":1,"ref":"/Users/vjagdale/workspace/test-profiles/sensitive-input/controls/example.rb"},"waiver_data":{},"results":[{"status":"passed","code_desc":"test123 is expected to eq \"test123\"","run_time":0.000117,"start_time":"2022-05-16T17:02:22+05:30","resource_class":"Object","resource_params":"[]","resource_id":"test123"}]}],"status":"loaded","status_message":""}],"statistics":{"duration":0.004042},"version":"5.15.1"}
```

**Comment by karikarshivani** [comment]
Thanks for the update @Vasu1105, I should probably clarify. Let's say that there's an InSpec **Profile A** with the following inspec.yml:
```
name: profile-a
summary: InSpec baseline profile
inputs:
  - name: sensitive-input
    value: test1234
    sensitive: true
```
And another InSpec **Profile B** that's an overlay with the following inspec.yml:
```
name: profile-b
summary: InSpec overlay profile
depends:
  - name: profile-a
    path: ../profile-a
```
This allows automatic access to inputs in Profile A when executing Profile B - so we usually don't redeclare the inputs in Profile B unless we are overriding the default values. We declare certain inputs in Profile A and add the inputs section in Profile B only when we need to declare new inputs/defaults that are profile B-specific. However, if we want the same inputs to be sensitive in both Profile A and B, we have to declare the inputs and mark them as sensitive in both the profiles. It makes more sense to just set it as sensitive once in the baseline and letting all the overlays inherit the input sensitivity without needing to add an inputs section every time only to re-iterate that the inputs are still sensitive.

---

Note: What I mentioned in the first comment (which you used to reproduce the error) was a temporary workaround by declaring the inputs in the overlay. Please lmk if you have any further questions. Thank you so much!
