### ISSUE TITLE
Regression on inputs - current main - iterators on arrays

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#6077]
There seems to be a regression with inputs being dereferenced in control blocks:

```yaml
name: my_nginx
title: InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile
version: 0.1.0
supports:
  platform: os

inputs:
  - name: nginx_version
    type: string
    value: 1.10.3

  - name: nginx_modules
    type: array
    value:
      - http_ssl
      - stream_ssl
      - mail_ssl
```

```ruby
control 'nginx-modules' do
  impact 1.0
  title 'NGINX modules'
  desc 'The required NGINX modules should be installed.'
  
  describe nginx do
    input('nginx_modules').each do |current_module|
      its('modules') { should include current_module }
    end
  end
end
```
Is not dereferencing the input correctly, however, if I assign the input to a local instance variable,

```ruby
control 'nginx-modules' do
  impact 1.0
  title 'NGINX modules'
  desc 'The required NGINX modules should be installed.'
  my_modules = input('nginx_modules')
  describe nginx do
    my_moduels.each do |current_module|
      its('modules') { should include current_module }
    end
  end
end
```
Works around the issue.

This is also still an issue inside describe.one blocks as well I think.
