### ISSUE TITLE
Add relative_path to url fetcher

### ISSUE THREAD

**Issue by ejaronne** [inspec/inspec#6127]
Similar to this:
```
depends:
- name: cms-ars-5.0-moderate-red-hat-enterprise-linux-8-stig-overlay
  git: https://github.com/ejaronne/cms-ars-5.0-red-hat-enterprise-linux-8-stig-overlay.git
  relative_path: cms-ars-5.0-moderate-red-hat-enterprise-linux-8-stig-overlay
```

requesting this as prototyped here: https://github.com/ejaronne/cms-ars-5.0-red-hat-enterprise-linux-8-stig-overlay/blob/desired-url-relative-path/inspec.yml:

```
depends:
- name: cms-ars-5.0-moderate-red-hat-enterprise-linux-8-stig-overlay
  url: https://github.com/ejaronne/cms-ars-5.0-red-hat-enterprise-linux-8-stig-overlay/archive/master.tar.gz
  relative_path: cms-ars-5.0-moderate-red-hat-enterprise-linux-8-stig-overlay
```

Why? In operational deployments of inspec, git is not always available, and if it is, then a current [bug ](https://github.com/inspec/inspec/issues/6064) requires one to perform a "git init" wherever inspec is invoked.

Our desire is to be able to run this overlay as such:
```
BASELINE=Moderate inspec exec https://github.com/ejaronne/cms-ars-5.0-red-hat-enterprise-linux-8-stig-overlay/archive/master.tar.gz
```
We strive to give users the option to run remotely from github without downloading or cloning the profile repo. We also want to be able to house multiple profiles (in this case tailoring overlays) within a single repository, similar to the impetus of the git fetcher's relative_path feature. This would support running against a cloned, downloaded, or remote profile repository, but is still a little inefficient when downloaded/cloned since it would reaching back out to the remote repository again and again for dependencies.

#5647 is also an issue affecting any of our overlays, thanks
