### ISSUE TITLE
Dependent profiles are not found when profile version does not follow semver

### ISSUE THREAD

**Issue by rlakey** [inspec/inspec#6409]
In InSpec 5.21.29 dependent profiles specified by path that do not have version failed to run with the following error

```
ERROR: Failed to load profile vmware-vcsa-7.0-stig-baseline: Failed to load source for controls/photon.rb: Cannot load 'photon' since it is not listed as a dependency of vmware-vcsa-7.0-stig-baseline.

Dependencies available from this context are:
    eam-1.0.4
    lookup-1.0.4
    perfcharts-1.0.4
    photon-3.0 Release 1 Version 5
    postgres-1.0.4
    rhttpproxy-1.0.4
    sts-1.0.4
    vami-1.0.4
    vsphere-ui-1.0.4
```

# Describe the problem
Profiles with dependent profiles should run those profiles without having to specify a version.

inspec.yml depends block for the profile generating the error that worked in prior versions without issue.

```
depends:
  - name: eam
    path: eam
  - name: lookup
    path: lookup
  - name: perfcharts
    path: perfcharts
  - name: photon
    path: ../vmware-photon-3.0-stig-inspec-baseline
  - name: postgres
    path: postgresql
  - name: rhttpproxy
    path: rhttpproxy
  - name: sts
    path: sts
  - name: vami
    path: vami
  - name: vsphere-ui
    path: ui
```

Possibly related to https://github.com/inspec/inspec/pull/6377
