### ISSUE TITLE
Using its('strip') on a string is not returning the right error.

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#778]
### Description

Using its('strip') on a string is not returning the right error. This impacts CIS profile execution, too

```
Failures:

  1) x86_64
 strip should eq "x86_64"
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

       expected: "x86_64"
            got: "strip"

       (compared using ==)
     # strip.rb:3:in `block (3 levels) in load'
     # /root/.chefdk/gem/ruby/2.1.0/gems/inspec-0.23/lib/inspec/runner_rspec.rb:66:in `run'
     # /root/.chefdk/gem/ruby/2.1.0/gems/inspec-0.23/lib/utils/base_cli.rb:70:in `run_tests'
     # /root/.chefdk/gem/ruby/2.1.0/gems/inspec-0.23/lib/inspec/cli.rb:111:in `exec'
```
### InSpec and Platform Version

Tell us which version of InSpec (`inspec version` or SHA of a commit) and Operating System distribution you are using
### Replication Case

It can be replicated with:

```
describe command("uname -m").stdout do
      its("strip") { should_not eq "x86_64" }
    end
```
### Possible Solutions

The following code works as expected:

```
describe command("uname -m").stdout.strip do
  it { should_not eq "x86_64" }
end
```
