### ISSUE TITLE
Transitive dependency loading

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#915]
### Description

As discussed in #888, we'll support transitive dependencies (A pulls B pulls C). All urls need to be vendored in a way that they do not conflict on disc. The RFC describes two phases, a resolution phase and an execution phase. This ticket describes the resolution phase, where required parts for execution are vendored locally. Assume we have the following `inspec.yml`

_inspec.yml_

```
name: inheritance
version: 1.0.0
supports:
  - os-family: unix
depends:
  - name: profile
    path: ../profile
  - name: ssh 
    github: dev-sec/tests-ssh-hardening
  - name: os
    supermarket: dev-sec/os-hardening
```

During resolution phase, we resolve all dependencies and built up a dependency graph. This graph is required to implement proper scoping for attributes, controls and resources later on. A sample `inspec.lock` could look like:

_inspec.lock_

The lock file is a yml file as well and includes resolved locations

```
dependencies:
  - name: profile
    path: ../profile
  - name: ssh 
    url: https://github.com/dev-sec/tests-ssh-hardening/archive/c2463115b3f7c254cbab9ddd7a7d215cdb843de1.zip
  - name: os
    git: https://github.com/dev-sec/tests-os-hardening.git
    revision: da3a1b6ce8a845d6818152a824e123c2445c355f

graph:
  inheritance:
    uses:
      profile 
      ssh
        uses:
          otherprofile
      os
```

InSpec should download all dependencies in a local cache directory. The global cache can be used with the `-g` or `--global` option.
- `/current/pwd/.cache/name-*sha256*`
- `~/.inspec/.cache/name-*sha256*`

The following commands can be used to download all dependencies:
- `inspec vendor` - is creating the lock file and vendors all dependencies into a local cache
- `inspec vendor -g` - is creating the lock file and vendors all dependencies into the global cache 

_Dependency resolution mechanism_

Instead of a constraint-resolution mechanism, we use a mechanism to fetch the latest-suitable version. This will require us to allow the loading of multiple profiles with the same name but different version at the same time. Eg. if we have a version dependency `>= 2.3` and the following versions are available: `2.4`, `2.3.1`, `2.2`, we would always fetch `2.4`. If a dependency in that tree depends on a specific version, we would load this as well.

Some open questions:
- should the cache only contain zip/tar files (Would imply that we archive a local path before execution?)
- if I run `inspec exec http://url/to/my/profile`, should we cleanup the cache at the end?
### InSpec and Platform Version

0.30.0
